import { TourStep, TourConfig, TOUR_IDS } from './types';

export const adminTourSteps: TourStep[] = [
  {
    target: '[data-tour="dashboard-container"]',
    content: '',
    title: '',
    placement: 'center',
    disableBeacon: true,
    route: '/dashboard',
    spotlightPadding: 0,
    locale: {
      skip: 'tour.skip',
    },
  },
  {
    target: '[data-tour="quick-actions"]',
    content: '',
    title: '',
    placement: 'bottom',
    disableBeacon: true,
    route: '/dashboard',
    spotlightPadding: 8,
  },
  {
    target: '[data-tour="table-grid"]',
    content: '',
    title: '',
    placement: 'right',
    disableBeacon: true,
    route: '/pos',
    spotlightPadding: 8,
  },
  {
    target: '[data-tour="menu-panel"]',
    content: '',
    title: '',
    placement: 'left',
    disableBeacon: true,
    route: '/pos',
    spotlightPadding: 8,
  },
  {
    target: '[data-tour="order-cart"]',
    content: '',
    title: '',
    placement: 'left',
    disableBeacon: true,
    route: '/pos',
    spotlightPadding: 8,
  },
  {
    target: '[data-tour="product-list"]',
    content: '',
    title: '',
    placement: 'bottom',
    disableBeacon: true,
    route: '/admin/menu',
    spotlightPadding: 8,
  },
  {
    target: '[data-tour="add-category"]',
    content: '',
    title: '',
    placement: 'bottom',
    disableBeacon: true,
    route: '/admin/menu',
    spotlightPadding: 8,
  },
  {
    target: '[data-tour="qr-management"]',
    content: '',
    title: '',
    placement: 'bottom',
    disableBeacon: true,
    route: '/admin/qr-codes',
    spotlightPadding: 8,
  },
  {
    target: '[data-tour="qr-download"]',
    content: '',
    title: '',
    placement: 'bottom',
    disableBeacon: true,
    route: '/admin/qr-codes',
    spotlightPadding: 8,
  },
  {
    target: '[data-tour="view-toggle"]',
    content: '',
    title: '',
    placement: 'bottom',
    disableBeacon: true,
    route: '/admin/tables',
    spotlightPadding: 8,
  },
  {
    target: '[data-tour="floor-plan-3d"]',
    content: '',
    title: '',
    placement: 'top',
    disableBeacon: true,
    route: '/admin/tables',
    spotlightPadding: 8,
  },
  {
    target: '[data-tour="settings-nav"]',
    content: '',
    title: '',
    placement: 'right',
    disableBeacon: true,
    route: '/admin/settings/subscription',
    spotlightPadding: 8,
  },
  {
    target: 'body',
    content: '',
    title: '',
    placement: 'center',
    disableBeacon: true,
    spotlightPadding: 0,
    styles: {
      spotlight: {
        display: 'none',
      },
    },
  },
];

export const adminTour: TourConfig = {
  id: TOUR_IDS.ADMIN,
  name: 'Admin Tour',
  steps: adminTourSteps,
};

export default adminTour;
