export enum DeliveryPlatform {
  YEMEKSEPETI = 'YEMEKSEPETI',
  GETIR = 'GETIR',
  TRENDYOL = 'TRENDYOL',
  MIGROS = 'MIGROS',
}

export enum PlatformLogDirection {
  INBOUND = 'INBOUND',
  OUTBOUND = 'OUTBOUND',
}

export enum PlatformLogAction {
  ORDER_RECEIVED = 'ORDER_RECEIVED',
  ORDER_ACCEPTED = 'ORDER_ACCEPTED',
  ORDER_REJECTED = 'ORDER_REJECTED',
  ORDER_PREPARING = 'ORDER_PREPARING',
  ORDER_READY = 'ORDER_READY',
  ORDER_PICKED_UP = 'ORDER_PICKED_UP',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  STATUS_UPDATE = 'STATUS_UPDATE',
  AUTH_REFRESH = 'AUTH_REFRESH',
  MENU_SYNC = 'MENU_SYNC',
  ITEM_AVAILABILITY = 'ITEM_AVAILABILITY',
  RESTAURANT_OPEN = 'RESTAURANT_OPEN',
  RESTAURANT_CLOSE = 'RESTAURANT_CLOSE',
  CONNECTION_TEST = 'CONNECTION_TEST',
  ORDER_POLL = 'ORDER_POLL',
}
