export {
  generateChairsForTable,
  generateAllChairs,
  calculateTableCapacity,
  type GeneratedChair,
} from './chairGenerator'

export {
  selectVariation,
  getLegGeometry,
  getTopGeometry,
  getMaterialColors,
  generateTableConfiguration,
  TABLE_STYLE_PRESETS,
  type TableStylePreset,
  type TableConfiguration,
  type LegGeometry,
  type TopGeometry,
} from './variationEngine'

export {
  generateCornerPlants,
  generateTableLamps,
  generateWallDecor,
  generateAllDecor,
  removeAutoGeneratedDecor,
  type DecorType,
} from './decorGenerator'

// Townscaper-style procedural floor & wall system
export {
  cellKey,
  parseKey,
  getNeighborMask,
  hasNeighbor,
  getTileVariant,
  computeFloorTiles,
  getFloorBounds,
  isOnFloor,
  getHeightAt,
  floodFillCells,
  generateRectangularFloor,
  generateDefaultFloor,
  NEIGHBOR_MASKS,
  MAX_BUILDING_HEIGHT,
  type FloorCell,
  type FloorTile,
  type FloorTileVariant,
} from './floorCellManager'

export {
  findWallEdges,
  generateWalls,
  getTotalWallLength,
  isBlockedByWall,
  type WallDirection,
  type WallType,
  type WallEdge,
  type WallSegment,
  type WallCorner,
  type GeneratedWalls,
} from './wallGenerator'

// Stair generator
export {
  canPlaceStair,
  getNeighborPosition,
  getStairLowerCell,
  getStairRotation,
  computeStairGeometry,
  stairKey,
  parseStairKey,
  hasStairAtEdge,
  getOppositeSide,
  STEPS_PER_LEVEL,
  STEP_HEIGHT,
  STEP_DEPTH,
  STAIR_WIDTH,
  STAIR_COLOR,
  type StairStepGeometry,
} from './stairGenerator'

// Railing generator
export {
  generateRailings,
  computeRailingPosts,
  computeRailingTop,
  RAILING_HEIGHT,
  RAILING_POST_THICKNESS,
  RAILING_POST_SPACING,
  RAILING_COLOR,
  RAILING_TOP_THICKNESS,
  type RailingPostGeometry,
  type RailingTopGeometry,
} from './railingGenerator'
