export default {
  "index": "Genel Bakış",
  "dashboard": "Kontrol Paneli",
  "pos": "POS (Satış Ekranı)",
  "kitchen": "Mutfak Ekranı (KDS)",
  "orders": "Siparişler",
  "tables": "Masalar & Kat Planı",
  "menu": "Menü Yönetimi",
  "qr-menu": "QR Menü",
  "qr-codes": "QR Kodları",
  "customers": "Müşteriler",
  "reservations": "Rezervasyonlar",
  "users": "Kullanıcılar & Roller",
  "personnel": "Personel",
  "stock": "Stok & Envanter",
  "invoices": "Faturalar",
  "reports": "Raporlar",
  "analytics": "Analitik",
  "branches": "Şubeler",
  "devices": "Cihazlar",
  "bridges": "Bridge'ler",
  "health": "Sistem Durumu",
  "fiscal-recovery": "Mali Kurtarma",
  "settings": "Ayarlar",
};
