// Components
export { VoxelCanvas } from './components/VoxelCanvas'
export { VoxelWorld } from './components/VoxelWorld'
export { VoxelWorldView } from './components/VoxelWorldView'
export { VoxelFloor } from './components/VoxelFloor'
export { VoxelWalls } from './components/VoxelWalls'
// Procedural Components (Townscaper-style)
export { ProceduralFloor } from './components/ProceduralFloor'
export { ProceduralWalls } from './components/ProceduralWalls'
export { ProceduralStairs } from './components/ProceduralStairs'
export { ProceduralRailings } from './components/ProceduralRailings'
export { InteractiveGrid } from './components/InteractiveGrid'
export { OrbitCamera } from './components/camera/OrbitCamera'
export { HeatmapOverlay, createHeatmapFromPoints, createOccupancyHeatmap } from './components/HeatmapOverlay'
export type { HeatmapOverlayProps, HeatmapColorScheme } from './components/HeatmapOverlay'

// Editor
export { EditorToolbar } from './components/editor/EditorToolbar'
export { ObjectLibrary } from './components/editor/ObjectLibrary'
export { MinimalToolbar } from './components/editor/MinimalToolbar'
export { SimplifiedDrawer } from './components/editor/SimplifiedDrawer'

// Interaction (TinyGlade-style)
export { ManipulationHandles, HandleMesh, GhostPreview, SnapGuides, SnapGuide } from './components/interaction'

// Shaders (Stylized rendering)
export {
  StylizedMaterial,
  WoodMaterial,
  DarkWoodMaterial,
  MetalMaterial,
  PlantMaterial,
  FabricMaterial,
  STYLIZED_PALETTE,
} from './shaders'
export type { StylizedMaterialProps } from './shaders'

// Effects
export { PostprocessingEffects } from './components/effects/PostprocessingEffects'

// Map 2D
export { Map2DView, Map2DCanvas, Map2DObject as Map2DObjectComponent, Map2DToolbar, Map2DObjectProperties } from './components/map-2d'

// POS Floor Plan
export { POSFloorPlanView, POSMap2DView, POSMap2DTable } from './components/pos'

// Mini Maps
export { MiniMap2D, MiniMap3D } from './components/mini-maps'

// Objects
export { VoxelTableObject } from './components/objects/VoxelTable'
export { VoxelChair } from './components/objects/VoxelChair'
export { VoxelKitchen } from './components/objects/VoxelKitchen'
export { VoxelBar } from './components/objects/VoxelBar'
export { VoxelDecor } from './components/objects/VoxelDecor'
export { VoxelModelObject } from './components/objects/VoxelModelObject'
export { ModelLoadingPlaceholder } from './components/objects/ModelLoadingPlaceholder'
export { InstancedModels, GroupedInstancedModels, shouldUseInstancing } from './components/objects/InstancedModels'

// Hooks
export { useVoxelWorld } from './hooks/useVoxelWorld'
export { useTablePositionSync } from './hooks/useTablePositionSync'
export { useLayout, useUpdateLayout, useUpdateTablePosition, useTablesWithPositions } from './hooks/useLayoutsApi'
export { useVoxelSocket } from './hooks/useVoxelSocket'
export { useModelLoader, preloadModel, clearModelCache } from './hooks/useModelLoader'
export { useModelAnimation } from './hooks/useModelAnimation'
export { useHistory } from './hooks/useHistory'
export { useManipulationGestures } from './hooks/useManipulationGestures'
export { useFloorEditor } from './hooks/useFloorEditor'

// Utils
export { serializeLayout, deserializeLayout, compressWorldData, decompressWorldData, calculateLayoutChecksum } from './utils/worldSerializer'
export { getMemoryStats, clearAllCache, preloadModels } from './utils/modelMemoryManager'
export { voxelToMap2D, map2DToVoxelPosition, voxelObjectsToMap2D, snapToGrid, getObjectDimensions } from './utils/map2dAdapter'
export { calculateSnap, calculateResizeSnap, DEFAULT_SNAP_CONFIG } from './utils/snapEngine'

// Procedural Generation
export {
  generateChairsForTable,
  generateAllChairs,
  calculateTableCapacity,
  selectVariation,
  getLegGeometry,
  getTopGeometry,
  getMaterialColors,
  generateTableConfiguration,
  TABLE_STYLE_PRESETS,
  generateCornerPlants,
  generateTableLamps,
  generateWallDecor,
  generateAllDecor,
  removeAutoGeneratedDecor,
  // Townscaper-style floor & wall system
  cellKey,
  parseKey,
  getNeighborMask,
  hasNeighbor,
  getTileVariant,
  computeFloorTiles,
  getFloorBounds,
  isOnFloor,
  getHeightAt,
  floodFillCells,
  generateRectangularFloor,
  generateDefaultFloor,
  NEIGHBOR_MASKS,
  MAX_BUILDING_HEIGHT,
  findWallEdges,
  generateWalls,
  getTotalWallLength,
  isBlockedByWall,
  // Stair generator
  canPlaceStair,
  getNeighborPosition,
  getStairLowerCell,
  getStairRotation,
  computeStairGeometry,
  stairKey,
  parseStairKey,
  hasStairAtEdge,
  getOppositeSide,
  STEPS_PER_LEVEL,
  STEP_HEIGHT,
  STEP_DEPTH,
  STAIR_WIDTH,
  STAIR_COLOR,
  // Railing generator
  generateRailings,
  computeRailingPosts,
  computeRailingTop,
  RAILING_HEIGHT,
  RAILING_POST_THICKNESS,
  RAILING_POST_SPACING,
  RAILING_COLOR,
  RAILING_TOP_THICKNESS,
} from './utils/procedural'
export type {
  GeneratedChair,
  TableStylePreset,
  TableConfiguration,
  LegGeometry,
  TopGeometry,
  DecorType,
  // Procedural floor types
  FloorCell,
  FloorTile,
  FloorTileVariant,
  // Procedural wall types
  WallDirection,
  WallType,
  WallEdge,
  WallSegment,
  WallCorner,
  GeneratedWalls,
  // Stair types
  StairStepGeometry,
  // Railing types
  RailingPostGeometry,
  RailingTopGeometry,
} from './utils/procedural'

// History
export {
  createHistoryManager,
  pushState,
  undo as historyUndo,
  redo as historyRedo,
  canUndo as historyCanUndo,
  canRedo as historyCanRedo,
  clearHistory as historyClearHistory,
} from './utils/historyManager'
export type { HistoryState, HistoryManager } from './utils/historyManager'

// Plugins
export { registerPlugin, unregisterPlugin, getPlugins, getEnabledPlugins, togglePlugin, getPlugin } from './plugins/map2dPlugins'

// Data
export { MODEL_LIBRARY, MODEL_CATEGORIES, getModelsByCategory, getModelById } from './data/modelLibrary'

// Store
export { useVoxelStore } from './store/voxelStore'

// Types
export type {
  VoxelObjectType,
  EditorTool,
  VoxelPosition,
  VoxelRotation,
  VoxelObject,
  VoxelTable,
  WorldDimensions,
  RestaurantLayout,
  VoxelWorldState,
  VoxelWorldActions,
  VoxelStore,
  LibraryItem,
  ModelCategory,
  AnimationConfig,
  ModelConfig,
  VoxelModelObject as VoxelModelObjectType,
  ModelLibraryItem,
  // TinyGlade-style types
  HandleId,
  ManipulationMode,
  ManipulationState,
  SizeConstraints,
  ResizableObject,
  TableLegStyle,
  TableTopShape,
  TableMaterial,
  TableVariation,
  SnapConfig,
  SnapResult,
  SnapGuide as SnapGuideType,
  // Stair and railing types
  StairSide,
  StairSegment,
  RailingSegment,
} from './types/voxel'

export type {
  AnimationState,
  AnimationControls,
} from './hooks/useModelAnimation'

export type {
  ModelLoadResult,
} from './hooks/useModelLoader'

export {
  VOXEL_COLORS,
  VOXEL_SIZE,
  DEFAULT_WORLD_DIMENSIONS,
  DEFAULT_CAMERA_POSITION,
  DEFAULT_CAMERA_ZOOM,
  FURNITURE_LIBRARY,
} from './types/voxel'

// Map2D Types
export type {
  Map2DConfig,
  Map2DObject,
  Map2DViewState,
  Map2DPlugin,
  Map2DPluginHooks,
  Map2DPluginDefinition,
} from './types/map2d'

export {
  DEFAULT_MAP2D_CONFIG,
  DEFAULT_MAP2D_VIEW_STATE,
  MAP2D_COLORS,
} from './types/map2d'
