// Marketing image map. Keys are stable; sources are chosen by the images' REAL
// content (the source filenames are misleading — see design spec §2). Optimized
// webp derivatives are generated by scripts/optimize-marketing-images.mjs into
// public/marketing/ and referenced here by absolute public path.
//
// kind: 'scene'  -> photo/scene background; render inside a framed device card.
//       'cutout' -> object on a light/flat field; render directly with a glow.

export type ImgKind = "scene" | "cutout";

export interface Img {
  src: string; // large webp (public path)
  srcSm: string; // small webp (public path)
  alt: string;
  w: number;
  h: number;
  kind: ImgKind;
}

export type ImgKey =
  | "heroTablet"
  | "mascot"
  | "posTerminal"
  | "qrStand"
  | "kdsChef"
  | "kdsCooking"
  | "posChef"
  | "mascotServe"
  | "deliveryScooter"
  | "deliveryCity"
  | "reportPhone"
  | "chartIcon"
  | "analytics"
  | "cloudNetwork"
  | "cloudServers"
  | "dioramaInterior"
  | "dioramaBuilding"
  | "shield"
  | "mascotShield"
  | "supportAgent"
  // Real product screenshots (captured from the live app, Turkish UI)
  | "screenKds"
  | "screenPos"
  | "screenDashboard"
  | "screenTables"
  | "screenQr";

const mk = (
  key: string,
  alt: string,
  w: number,
  h: number,
  kind: ImgKind,
): Img => ({
  // NOTE: served from /brand/ — NOT /marketing/, which the prod host relays
  // (301) to the decoupled marketing.hummytummy.com app. See images.test.ts guard.
  src: `/brand/${key}-lg.webp`,
  srcSm: `/brand/${key}-sm.webp`,
  alt,
  w,
  h,
  kind,
});

// Real product screenshots live under /brand/screens/ (same relay caveat).
const shot = (key: string, alt: string, w: number, h: number): Img => ({
  src: `/brand/screens/${key}-lg.webp`,
  srcSm: `/brand/screens/${key}-sm.webp`,
  alt,
  w,
  h,
  kind: "scene",
});

export const IMG: Record<ImgKey, Img> = {
  heroTablet: mk(
    "heroTablet",
    'HummyTummy tablet sipariş ekranı — menü, sepet ve "Siparişi Tamamla" butonu',
    1000,
    1250,
    "scene",
  ),
  mascot: mk(
    "mascot",
    "HummyTummy şef maskotu, başparmak yukarı",
    1000,
    1333,
    "cutout",
  ),
  posTerminal: mk(
    "posTerminal",
    "Dokunmatik POS terminalinde HummyTummy menü ekranı ve kart okuyucu",
    1000,
    1250,
    "scene",
  ),
  qrStand: mk(
    "qrStand",
    "Restoran masasında QR menü standı",
    1000,
    1250,
    "scene",
  ),
  kdsChef: mk(
    "kdsChef",
    "Şef, mutfak ekranında (KDS) sipariş durumlarını takip ediyor",
    1000,
    1250,
    "scene",
  ),
  kdsCooking: mk(
    "kdsCooking",
    "Şef ocakta yemek hazırlarken üstteki KDS panosunda canlı siparişler",
    1000,
    750,
    "scene",
  ),
  posChef: mk(
    "posChef",
    "Şef, POS terminalinde sipariş alıyor",
    1000,
    750,
    "scene",
  ),
  mascotServe: mk(
    "mascotServe",
    "HummyTummy şef maskotu tabakta burger sunuyor",
    1000,
    1250,
    "scene",
  ),
  deliveryScooter: mk(
    "deliveryScooter",
    "Paket servis scooter’ı ile teslimat",
    1000,
    750,
    "cutout",
  ),
  deliveryCity: mk(
    "deliveryCity",
    "Şehirde teslimat scooter’ı",
    1000,
    1250,
    "scene",
  ),
  reportPhone: mk(
    "reportPhone",
    "Telefonda günlük ciro grafiği ve en çok satan ürünler",
    1000,
    1250,
    "cutout",
  ),
  chartIcon: mk("chartIcon", "Yükselen satış grafiği", 1000, 1000, "cutout"),
  analytics: mk("analytics", "Satış analiz grafikleri", 1000, 1250, "cutout"),
  cloudNetwork: mk(
    "cloudNetwork",
    "Bulut tabanlı şube ağı",
    1000,
    1250,
    "cutout",
  ),
  cloudServers: mk(
    "cloudServers",
    "Bulut sunucu altyapısı",
    1000,
    1000,
    "cutout",
  ),
  dioramaInterior: mk(
    "dioramaInterior",
    "Restoran iç mekanı — salon ve açık mutfak",
    1000,
    750,
    "cutout",
  ),
  dioramaBuilding: mk(
    "dioramaBuilding",
    "İki katlı restoran binası",
    1000,
    1250,
    "cutout",
  ),
  shield: mk("shield", "Güvenlik kalkanı ve kilit", 1000, 1000, "cutout"),
  mascotShield: mk(
    "mascotShield",
    "HummyTummy şef maskotu güvenlik kalkanıyla",
    1000,
    1250,
    "cutout",
  ),
  supportAgent: mk(
    "supportAgent",
    "Kulaklıklı müşteri destek temsilcisi",
    1000,
    1250,
    "cutout",
  ),

  // ── Real product screenshots (Turkish UI, live demo data) ──────────
  screenKds: shot(
    "screenKds",
    "HummyTummy Mutfak Ekranı (KDS) — Beklemede / Hazırlanıyor / Hazır kolonlarında canlı sipariş kartları",
    1200,
    621,
  ),
  screenPos: shot(
    "screenPos",
    "HummyTummy POS satış ekranı — ürün grid’i ve sipariş sepeti",
    1200,
    621,
  ),
  screenDashboard: shot(
    "screenDashboard",
    "HummyTummy kontrol paneli — günlük ciro, sipariş ve masa özetleri",
    1200,
    621,
  ),
  screenTables: shot(
    "screenTables",
    "HummyTummy masa yönetimi — canlı masa durumları",
    1200,
    621,
  ),
  screenQr: shot(
    "screenQr",
    "HummyTummy QR menü — müşteri telefonunda menü ve sepet",
    390,
    844,
  ),
};
