// Deep-dive content for the module sub-pages (/ozellikler/:slug). The rich TR
// copy (hero/intro/blocks/how/advantages/faq) is authored + honesty-verified by
// the deep-dive workflow into moduleContent.generated.ts; the image +
// related-module wiring lives here (CONTENT_META). A fallback derives a minimal
// page from the base module so a page never breaks if copy is missing.

import type { ImgKey } from "./images";
import { MODULES, moduleBySlug } from "./modules";
import { GENERATED_CONTENT } from "./moduleContent.generated";

export interface ContentBlock {
  title: string;
  body: string;
  bullets: string[];
}

export interface HowStep {
  title: string;
  body: string;
}

export interface ModuleCopy {
  hero: { eyebrow: string; title: string; subtitle: string };
  intro: string;
  blocks: ContentBlock[];
  how: { heading: string; steps: HowStep[] };
  advantages: string[];
  faq: { q: string; a: string }[];
  ctaTitle: string;
}

export interface ModuleMeta {
  heroImage: ImgKey;
  blockImages: ImgKey[];
  related: string[];
}

// Image + related-module assignments (chosen by real image content).
export const CONTENT_META: Record<string, ModuleMeta> = {
  "qr-menu": {
    heroImage: "qrStand",
    blockImages: ["screenQr", "heroTablet"],
    related: ["pos-odeme", "masa-siparis", "entegrasyonlar"],
  },
  "pos-odeme": {
    heroImage: "posChef",
    blockImages: ["screenPos", "posTerminal"],
    related: ["qr-menu", "mutfak-ekrani-kds", "raporlar"],
  },
  "mutfak-ekrani-kds": {
    heroImage: "screenKds",
    blockImages: ["kdsChef", "kdsCooking"],
    related: ["pos-odeme", "masa-siparis", "stok-envanter"],
  },
  "masa-siparis": {
    heroImage: "dioramaInterior",
    blockImages: ["screenTables", "dioramaBuilding"],
    related: ["qr-menu", "rezervasyon", "coklu-sube"],
  },
  "stok-envanter": {
    heroImage: "chartIcon",
    blockImages: ["analytics", "posTerminal"],
    related: ["raporlar", "e-fatura", "entegrasyonlar"],
  },
  raporlar: {
    heroImage: "screenDashboard",
    blockImages: ["reportPhone", "analytics"],
    related: ["analitik", "stok-envanter", "coklu-sube"],
  },
  "coklu-sube": {
    heroImage: "dioramaBuilding",
    blockImages: ["cloudNetwork", "cloudServers"],
    related: ["raporlar", "donanim", "entegrasyonlar"],
  },
  entegrasyonlar: {
    heroImage: "deliveryScooter",
    blockImages: ["deliveryCity", "cloudNetwork"],
    related: ["e-fatura", "pos-odeme", "coklu-sube"],
  },

  // New modules
  rezervasyon: {
    heroImage: "dioramaInterior",
    blockImages: ["qrStand", "mascotServe"],
    related: ["masa-siparis", "garson-cagri", "qr-menu"],
  },
  "garson-cagri": {
    heroImage: "qrStand",
    blockImages: ["posChef", "mascotServe"],
    related: ["qr-menu", "pos-odeme", "musteri-sadakat"],
  },
  personel: {
    heroImage: "supportAgent",
    blockImages: ["mascot", "dioramaInterior"],
    related: ["raporlar", "coklu-sube", "analitik"],
  },
  "musteri-sadakat": {
    heroImage: "mascotServe",
    blockImages: ["reportPhone", "mascot"],
    related: ["qr-menu", "raporlar", "garson-cagri"],
  },
  analitik: {
    heroImage: "analytics",
    blockImages: ["reportPhone", "chartIcon"],
    related: ["raporlar", "stok-envanter", "coklu-sube"],
  },
  "e-fatura": {
    heroImage: "chartIcon",
    blockImages: ["analytics", "posTerminal"],
    related: ["pos-odeme", "entegrasyonlar", "raporlar"],
  },
  donanim: {
    heroImage: "cloudServers",
    blockImages: ["posTerminal", "cloudNetwork"],
    related: ["coklu-sube", "mutfak-ekrani-kds", "pos-odeme"],
  },
  marketplace: {
    heroImage: "dioramaBuilding",
    blockImages: ["chartIcon", "cloudNetwork"],
    related: ["entegrasyonlar", "donanim", "coklu-sube"],
  },
  guvenlik: {
    heroImage: "mascotShield",
    blockImages: ["shield", "cloudServers"],
    related: ["coklu-sube", "entegrasyonlar", "donanim"],
  },
};

// Rich, honesty-verified copy per module — generated by the deep-dive authoring
// pass (modules-sectors-copy workflow) into moduleContent.generated.ts.
export const MODULE_CONTENT: Record<string, ModuleCopy> = GENERATED_CONTENT;

/** Content for a slug, with a graceful fallback built from the base module. */
export function getModuleCopy(slug: string): ModuleCopy | null {
  if (MODULE_CONTENT[slug]) return MODULE_CONTENT[slug];
  const m = moduleBySlug(slug);
  if (!m) return null;
  return {
    hero: { eyebrow: m.title, title: m.tagline, subtitle: m.bullets[0] },
    intro: m.bullets.join(" "),
    blocks: [{ title: m.title, body: m.tagline, bullets: m.bullets }],
    how: { heading: "Nasıl çalışır?", steps: [] },
    advantages: m.bullets,
    faq: [],
    ctaTitle: "Bugün ücretsiz deneyin",
  };
}

export const MODULE_SLUGS = MODULES.map((m) => m.slug);
