// AUTO-GENERATED by the module-deepdive-copy workflow. Rich, honesty-verified
// TR deep-dive copy for /ozellikler/:slug. Do not edit by hand — regenerate.
import type { ModuleCopy } from "./moduleContent";

export const GENERATED_CONTENT: Record<string, ModuleCopy> = {
  "qr-menu": {
    hero: {
      eyebrow: "QR Menü",
      title: "Kağıt menü masrafına elveda, temassız siparişe merhaba",
      subtitle:
        "Misafiriniz masadaki karekodu telefonuyla okutsun; menünüz saniyeler içinde tarayıcıda açılsın. Kategorilere göz atsın, ürün detaylarını incelesin, sepetini oluşturup siparişini versin — hiçbir uygulama indirmeden.",
    },
    intro:
      "HummyTummy QR Menü, restoran ve kafenizin menüsünü misafirinizin cebine taşır. Masaya yerleştirdiğiniz karekod okutulduğunda menü telefonun tarayıcısında açılır; kategoriler, güncel fiyatlar, ürün görselleri, açıklamalar ve porsiyon bilgileri tertemiz bir düzende karşılarına gelir. Bir üründe fiyatı değiştirdiğinizde, yeni bir tabak eklediğinizde ya da bir kampanya başlattığınızda değişiklik o an menüye yansır — matbaaya gitmeden, tek bir sayfayı bile yeniden bastırmadan. Misafir aynı ekrandan sepetini oluşturur, siparişini gönderir, dilerse garson çağırır veya hesabını ister. Sizin için bu; azalan kağıt masrafı, hızlanan servis ve her masada daima güncel bir menü demektir.",
    blocks: [
      {
        title: "Her zaman güncel, sıfır baskı maliyeti",
        body: "Basılı menünün en büyük derdi, her küçük değişiklikte yeniden matbaaya gitme zorunluluğudur. QR Menü'de menünüz baştan sona dijitaldir: bir ürünün fiyatını güncellediğinizde, stoğu biten bir tabağı gizlediğinizde ya da yeni bir kampanya tanımladığınızda değişiklik o anda masadaki misafirin ekranına düşer. Sezon menüleri, günün yemeği veya hafta sonu kampanyaları arasında baskı maliyeti ödemeden, saniyeler içinde geçiş yaparsınız; menünüz her masada aynı ve daima günceldir.",
        bullets: [
          "Fiyat, ürün ve kampanya değişiklikleri anında tüm masalara yansır",
          "Kağıt menü baskı ve yeniden baskı masrafı tamamen ortadan kalkar",
          "Stoğu biten ürünü tek dokunuşla menüden gizleyin, yanlış siparişi önleyin",
          "Menü her masada eş zamanlı; yıpranmış, eksik ya da eski fiyatlı kart kalmaz",
        ],
      },
      {
        title: "5 dilde arayüz ve zengin ürün tanıtımı",
        body: "Menü arayüzü Türkçe, İngilizce, Rusça, Özbekçe ve sağdan-sola yazım destekli Arapça olmak üzere beş dilde sunulur; turistik bölgelerdeki işletmelerde misafir kendi dilinde rahatça gezinir. Her ürüne yüksek çözünürlüklü görsel, açıklama, porsiyon ve alerjen bilgisi ekleyebilir; marka renginiz, yazı tipiniz ve logonuzla menüyü işletmenize özel bir görünüme kavuşturabilirsiniz. Ürün adlarını ve açıklamalarını hangi dilde göstermek isterseniz o metni siz girersiniz.",
        bullets: [
          "Arayüz 5 dilde: Türkçe, İngilizce, Rusça, Özbekçe ve Arapça (RTL desteğiyle)",
          "Ürün başına yüksek çözünürlüklü görsel, açıklama, porsiyon ve alerjen bilgisi",
          "Marka rengi, yazı tipi, logo ve ızgara/liste/kompakt düzen seçenekleri",
          "Görsel, açıklama ve fiyat gösterimini ürün bazında açıp kapatma",
        ],
      },
      {
        title: "Masadan sipariş, garson çağrısı ve hesap isteme",
        body: "QR Menü yalnızca dijital bir liste değil; misafirin masasından hizmet aldığı temassız bir kanaldır. Misafir beğendiği ürünleri sepete ekler ve siparişini gönderir; sipariş anında sisteminize düşer ve mutfak ekranınızda görünür. Aynı ekrandan garson çağırabilir ya da hesabını isteyebilir — personelinizi el kaldırıp beklemeden doğru masaya yönlendirir. Masaya özel karekodlar sayesinde her sipariş, hangi masadan geldiği belli olacak şekilde otomatik işaretlenir.",
        bullets: [
          "Sepet oluşturma ve tek dokunuşla sipariş gönderme",
          "Menü ekranından garson çağırma ve hesap isteme talebi",
          "Masaya özel karekodla siparişin geldiği masayı otomatik eşleştirme",
          "Gelen siparişler sisteminize ve mutfak ekranınıza anında düşer",
        ],
      },
    ],
    how: {
      heading: "QR Menü nasıl çalışır?",
      steps: [
        {
          title: "Menünüzü hazırlayın",
          body: "Kategorilerinizi, ürünlerinizi, fiyatlarınızı, görsellerinizi ve açıklamalarınızı panelden girin. Renk, logo ve düzen ayarlarıyla menüyü markanıza uygun hale getirin.",
        },
        {
          title: "Karekodu masaya yerleştirin",
          body: "İşletmeniz için tek bir genel karekod ya da her masaya özel karekodlar oluşturun; çıktısını alıp sticker, masa ayaklığı veya kart olarak yerleştirin.",
        },
        {
          title: "Misafir okutur ve gezinir",
          body: "Misafir karekodu telefonunun kamerasıyla okutur; menü uygulama indirmeden tarayıcıda açılır. Kendi dilinde kategorilere bakar, ürün detaylarını görür ve sepetini oluşturur.",
        },
        {
          title: "Sipariş ve hizmet talebi düşer",
          body: "Misafir siparişini gönderir; sipariş sisteminize ve mutfak ekranınıza düşer. Garson çağrısı veya hesap talebi de aynı anda personelinize iletilir.",
        },
      ],
    },
    advantages: [
      "Uygulama indirme yok; karekodu okutan her misafir saniyeler içinde menüye ulaşır",
      "Kağıt menü baskı ve güncelleme masrafını tamamen ortadan kaldırır",
      "Fiyat, ürün ve kampanya değişiklikleri tüm masalara gerçek zamanlı yansır",
      "Turistik bölgeler için 5 dilli arayüz (Arapça RTL dahil)",
      "Masadan garson çağrısı ve hesap isteme ile daha hızlı, daha az bekleten servis",
      "Masaya özel karekodlarla sipariş-masa eşleştirmesi otomatik",
    ],
    faq: [
      {
        q: "Misafirin uygulama indirmesi gerekiyor mu?",
        a: "Hayır. Misafir yalnızca telefonunun kamerasıyla masadaki karekodu okutur; menü doğrudan tarayıcıda açılır. Hiçbir uygulama kurulumu ya da üyelik gerekmez.",
      },
      {
        q: "Menü kaç dilde görüntüleniyor?",
        a: "Menü arayüzü Türkçe, İngilizce, Rusça, Özbekçe ve Arapça (sağdan-sola) olmak üzere beş dilde sunulur. Ürün adı ve açıklamalarını ise siz girersiniz; bu içerikler otomatik çevrilmez, hangi dildeki metni göstermek isterseniz onu siz eklersiniz.",
      },
      {
        q: "Fiyat veya ürün değiştirdiğimde menüyü yeniden bastırmam gerekir mi?",
        a: "Hayır. Menü tamamen dijitaldir; panelden yaptığınız fiyat, ürün ve kampanya değişiklikleri anında masadaki menüye yansır. Baskı ya da yeniden baskı maliyeti yoktur.",
      },
      {
        q: "Misafir masadan sipariş verebilir mi, garson çağırabilir mi?",
        a: "Evet. Misafir menüden sepetini oluşturup siparişini gönderebilir; sipariş sisteminize ve mutfak ekranınıza düşer. Ayrıca aynı ekrandan garson çağırabilir veya hesabını isteyebilir.",
      },
      {
        q: "Siparişin hangi masadan geldiğini anlayabilir miyim?",
        a: "Evet. Masaya özel karekodlar oluşturduğunuzda her sipariş ilgili masayla otomatik eşleşir; böylece personeliniz doğru masaya doğru servisi yapar.",
      },
    ],
    ctaTitle: "Dakikalar içinde dijital QR menünüzü yayına alın",
  },
  "pos-odeme": {
    hero: {
      eyebrow: "POS & Ödeme",
      title: "Dokunmatik hızda satış, kuruşu kuruşuna doğru hesap",
      subtitle:
        "Siparişten ödemeye tek ekran: nakit ve kart kaydı, üç yöntemle hesap bölme, satır bazında KDV-dahil vergi ve müşterinin QR'dan online ödediği PayTR self-pay.",
    },
    intro:
      "Yoğun serviste kasa, işletmenin nabzının attığı yerdir; oradaki her saniyelik gecikme masaya, mutfağa ve müşteri memnuniyetine geri döner. HummyTummy POS & Ödeme, siparişi almaktan hesabı kapatmaya kadar tüm akışı tek bir dokunmatik ekranda toplar. Garson ürünü seçer, masayı yönetir, gerektiğinde hesabı böler ve ödemeyi kaydeder — kağıt adisyoya, hesap makinesine ya da kafadan toplama yapmaya gerek kalmadan. Nakit ile kartı ayrı ödeme yöntemleri olarak net biçimde ayırır, KDV'yi %0/%1/%10/%20 oranlarıyla satır satır doğru hesaplar ve dilerseniz müşterinin masadaki QR'dan kendi hesabını PayTR üzerinden çevrimiçi ödemesine izin verirsiniz. Sonuç: daha hızlı masa devri, daha az hesap hatası ve gün sonunda kasayla birbirini tutan rakamlar.",
    blocks: [
      {
        title: "Dokunmatik satış ekranı: siparişten ödemeye tek akış",
        body: "Servis yoğunluğunda hız her şeydir. HummyTummy'nin dokunmatik POS ekranı ürünlerinizi kategori kategori önünüze serer; masayı seçer, ürünleri büyük butonlarla eklersiniz ve aynı ekrandan ödemeye geçersiniz. Kağıt adisyo, ayrı hesap makinesi ve el yazısıyla toplam çıkarma derdi ortadan kalkar. Eklediğiniz her satır anında sisteme işlenir; böylece adisyo ve toplam her an günceldir, masaya bakan herkes aynı ve doğru hesabı görür. Masa içi, paket ve gel-al siparişlerini de aynı ekrandan ayrı ayrı yönetirsiniz.",
        bullets: [
          "Kategori ve ürünlere büyük dokunmatik butonlarla tek dokunuşta erişim",
          "Masa içi, paket veya gel-al siparişini seçip aynı ekrandan ödemeye geçiş",
          "Her ürün satırı anında kaydedilir; adisyo ve toplam sürekli güncel kalır",
          "Sipariş bazlı indirimi uygulayınca toplam otomatik yeniden hesaplanır",
        ],
      },
      {
        title: "Hesap bölme ve vergi: müşteri nasıl isterse öyle",
        body: 'Kalabalık bir masa "ayrı ayrı ödeyelim" dediğinde işler karışmasın. HummyTummy hesabı üç farklı şekilde bölmenizi sağlar: herkese eşit paylaştırma, ürün bazlı bölme (kim ne yediyse ona) veya elle girdiğiniz özel tutar. Aynı masada birden fazla ödemeyi birbirinden bağımsız kaydeder, kalan tutarı her adımda net görürsünüz. Vergi tarafında her satır KDV-dahil hesaplanır; %0, %1, %10 ve %20 oranlarını ürün bazında yönetir, toplamın içindeki KDV\'yi doğru dökümle gösterirsiniz. Nakit ve kart ödemelerini ayrı yöntemler olarak kaydettiğiniz için gün sonunda hangi tutarın nereden geldiği bellidir.',
        bullets: [
          "Üç bölme yöntemi: eşit paylaşım, ürün bazlı ve elle girilen özel tutar",
          "Satır bazında KDV-dahil vergi: %0, %1, %10 ve %20 oranları",
          "Nakit ve kartı ayrı ödeme yöntemi olarak kaydedip net döküm alma",
          "Aynı masada birden fazla ödemeyi bağımsız biçimde, kalanı görerek işleme",
        ],
      },
      {
        title: "Kasa güvenliği ve QR'dan PayTR self-pay",
        body: "Para hareketinin izi kaybolmasın. Onaylı kasa çekmecesi hareketleriyle her giriş ve çıkış kayıt altına alınır; para üstü, avans ya da gider gibi hareketleri sisteme işler, gün sonu sayımını tahmine değil gerçek veriye dayandırırsınız. Dilerseniz PayTR self-pay özelliğini açar, müşterinin masadaki QR kodundan kendi hesabını çevrimiçi ödemesine izin verirsiniz — sıra kasada beklemez, garson tahsilat için masaya gitmek zorunda kalmaz. Bu özellik opt-in'dir: PayTR üye işyeri hesabınızın olması ve ilgili ayarın açık olması gerekir. Kapalıyken ödemeleri her zamanki gibi kasadan, nakit ya da kendi kart cihazınızla alırsınız.",
        bullets: [
          "Onaylı kasa çekmecesi hareketleriyle her nakit giriş/çıkışının kaydı",
          "Para üstü, avans ve gideri işleyip gün sonu sayımını gerçek veriyle karşılaştırma",
          "PayTR self-pay: müşteri masadaki QR'dan kendi hesabını online öder (opt-in)",
          "Self-pay için PayTR üye işyeri hesabı ve özelliğin etkinleştirilmesi gerekir",
        ],
      },
    ],
    how: {
      heading: "POS & Ödeme nasıl çalışır?",
      steps: [
        {
          title: "Siparişi oluştur",
          body: "Masayı ya da paket/gel-al siparişini seç, dokunmatik ekrandan ürünleri ekle; her satır anında adisyoya işlenir ve toplam kendiliğinden güncellenir.",
        },
        {
          title: "Gerekirse hesabı böl",
          body: "Müşteri ayrı ödemek isterse hesabı eşit, ürün bazlı veya özel tutar olarak böl; dilersen sipariş bazlı indirimi uygula, toplam yeniden hesaplansın.",
        },
        {
          title: "Ödemeyi al",
          body: "Nakit veya kartı yöntem seçerek kaydet; kartta fiziksel tahsilatı kendi cihazından alırsın. Alternatif olarak müşteri masadaki QR'dan PayTR self-pay ile kendi hesabını online ödesin.",
        },
        {
          title: "Kasayı ve gün sonunu takip et",
          body: "Onaylı kasa çekmecesi hareketleriyle nakit akışını izle, gün sonu sayımını gerçek verilerle karşılaştırıp açık veya fazlayı anında gör.",
        },
      ],
    },
    advantages: [
      "Dokunmatik hızda satış, sıfır kağıt adisyo",
      "Üç yöntemle esnek hesap bölme: eşit, ürün bazlı, özel tutar",
      "Satır bazında KDV-dahil doğru vergi (%0/%1/%10/%20)",
      "Onaylı kasa çekmecesiyle şeffaf ve izlenebilir nakit yönetimi",
      "PayTR self-pay ile müşteri QR'dan kendi hesabını online öder (opt-in)",
      "Çoklu şubede aynı, tutarlı POS deneyimi",
    ],
    faq: [
      {
        q: "Kart ödemesini POS terminaliyle mi tahsil ediyorsunuz?",
        a: "Hayır. POS ekranı kartı bir ödeme yöntemi olarak kaydeder; fiziksel tahsilatı kendi kart/POS cihazınızdan alırsınız. Sistem üzerinden çevrimiçi tahsilat yalnızca PayTR self-pay ile yapılır.",
      },
      {
        q: "Hesabı hangi yöntemlerle bölebilirim?",
        a: "Üç yöntem sunuyoruz: herkese eşit paylaştırma, ürün bazlı bölme (kim ne aldıysa) ve elle girdiğiniz özel tutar. Aynı masada birden fazla ödemeyi bağımsız biçimde, kalan tutarı görerek kaydedebilirsiniz.",
      },
      {
        q: "KDV oranları nasıl işliyor?",
        a: "Vergi satır bazında ve KDV-dahil hesaplanır. Her ürüne %0, %1, %10 veya %20 oranını atarsınız; sistem toplamın içindeki KDV'yi doğru dökümle gösterir.",
      },
      {
        q: "Müşterinin kendi hesabını online ödemesi için ne gerekiyor?",
        a: "PayTR üye işyeri hesabınızın olması ve self-pay özelliğinin açık olması gerekir. Etkinleştirdiğinizde müşteri masadaki QR'dan kendi hesabını çevrimiçi öder; kapalıyken ödemeleri her zamanki gibi kasadan alırsınız.",
      },
      {
        q: "Nakit kasa hareketlerini takip edebilir miyim?",
        a: "Evet. Onaylı kasa çekmecesi hareketleriyle her giriş ve çıkışı kayıt altına alırsınız. Gün sonu sayımınızı gerçek kasa hareketleriyle karşılaştırarak açık ya da fazlayı kolayca görürsünüz.",
      },
    ],
    ctaTitle: "Kasanızı hızlandırın, hesabı müşterinize göre bölün",
  },
  "mutfak-ekrani-kds": {
    hero: {
      eyebrow: "Mutfak Ekranı (KDS)",
      title: "Mutfakta sipariş kaosuna son",
      subtitle:
        "Adisyon kağıdı, bağıra çağıra sipariş okuma ve unutulan masalar geride kaldı. Salondan, QR menüden veya POS'tan girilen her sipariş, verildiği anda mutfak ekranınıza canlı düşer; ekibiniz neyi, hangi masaya, ne zaman hazırlayacağını tek bakışta görür.",
    },
    intro:
      'HummyTummy Mutfak Ekranı (KDS), sipariş alınan her noktayı mutfağınıza gerçek zamanlı olarak bağlar. Garson POS\'ta siparişi onayladığı ya da müşteri masadaki QR menüden gönderdiği saniyede ürünler kalem kalem mutfak ekranında belirir; kimse kağıt fişin mutfağa ulaşmasını beklemez, hiçbir kalem gözden kaçmaz. Her sipariş için hazırlanıyor ve hazır durumu, ait olduğu masa ve o ana kadar geçen bekleme süresi ekranda net görünür; yeni bir sipariş düştüğünde sesli ve görsel uyarı ekibi anında haberdar eder. Yoğun serviste mutfağın nabzını tek ekrandan tutar, tabakların doğru sırayla çıkmasını sağlar ve müşteriye \\"siparişim ne oldu?\\" dedirtmezsiniz.',
    blocks: [
      {
        title: "Siparişler mutfağa anında, canlı düşer",
        body: "KDS'in kalbi, sipariş alınan noktayla mutfak arasındaki gerçek zamanlı bağlantıdır. Salondaki garson POS'ta siparişi onayladığında ya da müşteri masadaki QR menüden gönderdiğinde, ürünler Socket.IO altyapısı üzerinden mutfak ekranına aynı anda yansır. Fişin yazıcıdan çıkmasını, birinin mutfağa götürmesini veya sözlü iletilmesini beklemek yok; bilgi bir kez giriliyor ve doğrudan hazırlayacak kişinin önüne geliyor. Böylece yanlış okunan siparişler, atlanan kalemler ve mutfağa geç ulaşan fişlerin yol açtığı gecikmeler kökten azalır.",
        bullets: [
          "Sipariş verildiği anda ekranda: yazıcı fişi beklemeye ya da sözlü iletime gerek kalmaz",
          "POS, salon ve QR menüden gelen tüm siparişler tek mutfak ekranında toplanır",
          "Her kartta masa/sipariş bilgisi, ürünler ve adetler kalem kalem listelenir",
          "Bağlantı canlı tutulur; yeni sipariş kendiliğinden belirir, ekranı yenilemeye gerek yok",
        ],
      },
      {
        title: "Hazırlanıyor / hazır takibi, süre ve uyarılarla",
        body: 'Mutfak ekranı siparişi yalnızca göstermez, akışı yönetmenizi sağlar. Ekip her siparişi "hazırlanıyor" durumuna alır, tamamlandığında "hazır" olarak işaretler; böylece hangi siparişin sırada beklediği, hangisinin pişmekte olduğu ve hangisinin servise hazır olduğu tek bakışta bellidir. Her kartta o siparişin girişinden bu yana geçen süre göründüğü için uzayan siparişleri erken fark eder, bekleyen masaları gözden kaçırmazsınız. Yeni bir sipariş düştüğünde sesli ve görsel uyarı devreye girer; mutfak gürültülü ve ekrana sürekli bakılamayacak kadar yoğun olsa bile hiçbir sipariş fark edilmeden kalmaz.',
        bullets: [
          "Hazırlanıyor ve hazır durumlarıyla her siparişin akışın neresinde olduğu net",
          "Kart üzerindeki bekleme süresi görünür; uzayan siparişleri erkenden yakalarsınız",
          "Yeni sipariş için sesli + görsel uyarı: yoğun mutfakta bile gözden kaçmaz",
          "Hazır işaretlenen sipariş gerçek zamanlı olarak sisteme yansır, servis hızlanır",
        ],
      },
      {
        title: "Donanım ekranlarına yansır, her şube kendi mutfağını görür",
        body: "HummyTummy'nin cihaz ağı (device-mesh) sayesinde mutfak ekranı tek bir tarayıcı sekmesiyle sınırlı kalmaz; siparişler mutfağa kurduğunuz eşleşmiş donanım ekranlarına da yansır. Böylece hazırlık istasyonunun tam karşısına asacağınız büyük bir ekranda ekibiniz, elleri işteyken bile siparişleri rahatça takip eder. Çok şubeli işletmelerde her şube kendi mutfak ekranını görür: bir şubenin siparişleri diğerinin ekranına düşmez, her mutfak yalnızca kendi işini takip eder. Bu sürümde şube başına tek ve birleşik bir mutfak akışı çalışır; ızgara, bar, tatlı gibi ayrı istasyon ekranlarına bölme bulunmaz.",
        bullets: [
          "Cihaz ağıyla siparişler mutfaktaki donanım ekranına da yansıtılır",
          "Çok şubeli kurulumda her şube yalnızca kendi mutfak siparişlerini görür",
          "Şube başına tek, birleşik mutfak akışı: tüm siparişler tek yerde toplanır",
          "Ekranı mutfağın istediğiniz noktasına konumlandırıp elleri serbest bırakırsınız",
        ],
      },
    ],
    how: {
      heading: "Mutfak Ekranı nasıl çalışır?",
      steps: [
        {
          title: "Sipariş girilir",
          body: "Garson POS'tan siparişi onaylar ya da müşteri masadaki QR menüden gönderir. Sipariş tek bir kaynağa kaydedilir; ayrıca fiş yazdırmaya veya mutfağa elden iletmeye gerek kalmaz.",
        },
        {
          title: "Mutfak ekranına canlı düşer",
          body: "Kaydedilen sipariş anında mutfak ekranında ve eşleşmiş donanım ekranlarında belirir. Sesli ve görsel uyarı ekibi haberdar eder; kartta masa, ürünler ve adetler görünür.",
        },
        {
          title: "Ekip hazırlığı yönetir",
          body: 'Aşçı siparişi "hazırlanıyor" durumuna alır. Kart üzerinde geçen süre işlemeye başlar; aynı anda gelen birden çok sipariş, geliş sırası ve bekleme süresiyle takip edilir.',
        },
        {
          title: "Hazır işaretlenir, servise geçer",
          body: 'Sipariş tamamlandığında "hazır" olarak işaretlenir. Hazır durumu gerçek zamanlı olarak sisteme yansır ve servis ekibi masayı toplayarak döngüyü kapatır.',
        },
      ],
    },
    advantages: [
      "Kağıt adisyon ve sözlü sipariş iletiminin yarattığı hata ve gecikmeyi ortadan kaldırır",
      "Siparişler verildiği anda mutfakta belirir; servis süresi kısalır, masalar daha hızlı döner",
      "Sesli ve görsel uyarıyla yoğun serviste hiçbir sipariş gözden kaçmaz",
      "Hazırlanıyor/hazır durumu ve bekleme süresiyle mutfağın nabzını tek ekrandan tutarsınız",
      "Donanım ekranıyla eller serbest; ekranı mutfağın uygun noktasına konumlandırıp sürekli görünürlük sağlarsınız",
      "7/24 bulut ve kolay kurulum; çok şubeli işletmede her şube kendi mutfak akışını ayrı görür",
    ],
    faq: [
      {
        q: "Sipariş mutfağa ne kadar sürede düşer?",
        a: "Sipariş POS'tan onaylandığı ya da QR menüden gönderildiği anda, gerçek zamanlı bağlantı üzerinden mutfak ekranında belirir. Fiş yazdırma veya sözlü iletim beklemeye gerek kalmaz.",
      },
      {
        q: "Izgara, bar ve tatlı için ayrı ayrı ekran kurabilir miyim?",
        a: "Bu sürümde her şube için tek ve birleşik bir mutfak ekranı çalışır; tüm siparişler orada toplanır. İstasyon bazlı (ızgara/bar/tatlı ayrı ekran) yönlendirme bulunmaz, siparişleri tek akışta durum ve süreyle yönetirsiniz.",
      },
      {
        q: "Yeni sipariş geldiğini ekibim nasıl fark eder?",
        a: "Her yeni sipariş düştüğünde sesli ve görsel bir uyarı devreye girer. Mutfak gürültülü olsa ya da ekrana sürekli bakılamasa bile ekip anında haberdar olur.",
      },
      {
        q: "Mutfağa büyük bir dokunmatik ekran kurabilir miyim?",
        a: "Evet. Cihaz ağı (device-mesh) sayesinde siparişler eşleşmiş donanım ekranlarına da yansır; mutfağa astığınız büyük bir ekranda ekibiniz elleri serbest şekilde siparişleri takip eder.",
      },
      {
        q: "Birden fazla şubem var, siparişler birbirine karışır mı?",
        a: "Hayır. Her şube yalnızca kendi mutfak siparişlerini görür; bir şubenin siparişleri diğerinin ekranına düşmez. Her mutfak yalnızca kendi işini takip eder.",
      },
    ],
    ctaTitle: "Mutfağınızı canlı sipariş akışıyla tanıştırın",
  },
  "masa-siparis": {
    hero: {
      eyebrow: "Masa & Sipariş Yönetimi",
      title: "Salonun tamamı tek ekranda, her masanın durumu tek bakışta",
      subtitle:
        "Restoranınızın kat planını birebir dijitale taşıyın; boş, dolu ve rezerve masaları anlık renklerle görün, rezervasyonları tek yerden yönetin, misafirlerinizin QR menüden garson ya da hesap çağırmasını sağlayın. Kağıt masa planına, karışan rezervasyon defterine ve masalar arasında boşa koşturulan dakikalara son.",
    },
    intro:
      "Yoğun bir serviste en çok kaybedilen şey zamandır: hangi masa yeni boşaldı, hangisi hesap bekliyor, akşam 20:00 rezervasyonu hangi masaya yazılmıştı? HummyTummy Masa & Sipariş modülü, salonunuzun gerçek yerleşimini birebir dijitale taşıyarak bu soruların hepsini tek bakışta yanıtlar. Masaları sürükle-bırak ile yerleştirdiğiniz kat planında her masanın durumunu -boş, dolu, rezerve- canlı renklerle görür; kalabalık gruplar için masaları birleştirir, kalkan grupları yeniden ayırırsınız. Misafirleriniz QR menü üzerinden tek dokunuşla garson çağırabilir veya hesap isteyebilir; gelen rezervasyonları ise hem yönetim panelinden hem de herkese açık rezervasyon sayfanız üzerinden tek bir yerde toplarsınız. Kısacası salonun nabzını gerçek zamanlı tutan, personelinizi masalar arasında boşuna koşturmaktan kurtaran bütünleşik bir masa yönetim merkezi.",
    blocks: [
      {
        title: "Salonunuzu birebir dijitale taşıyan kat planı editörü",
        body: "Restoranınızın gerçek yerleşimini ekranda yeniden kurun. Masaları sürükle-bırak yöntemiyle istediğiniz noktaya konumlandırır, salonun düzenini ister kuşbakışı 2B ister gerçekçi 3B görünümde çalışırsınız. Her masanın rengi durumunu anlatır: boş, dolu ve rezerve masalar tek bakışta ayrışır, böylece personeliniz 'yeni gelen grubu nereye oturtalım' derdine düşmeden doğru masaya yönlenir. Şubeniz büyüdükçe ya da salon düzenini değiştirdikçe planı dilediğiniz kadar yeniden şekillendirebilirsiniz. Kat planı canlı çalışır; bir masanın durumu değiştiği anda ekran kendiliğinden güncellenir, siz de salonu bizzat dolaşmadan anlık doluluğunuzu görürsünüz.",
        bullets: [
          "Sürükle-bırak ile masa yerleştirme ve salon düzenini birebir kurma",
          "Kuşbakışı 2B ve gerçekçi 3B görünüm arasında seçim",
          "Boş / dolu / rezerve masaları renklerle ayıran canlı durum takibi",
          "Değişen düzene göre planı istediğiniz zaman yeniden şekillendirme",
        ],
      },
      {
        title: "Kalabalık gruplar için masa birleştirme ve bölme",
        body: "Servis akışı hiçbir zaman sabit değildir; sekiz kişilik bir grup gelir, iki masa yan yana birleşir, sonra bir kısmı kalkıp masalar yeniden ayrılır. HummyTummy'de birkaç dokunuşla masaları birleştirerek büyük gruplara tek bir düzen kurar, ihtiyaç bittiğinde birleştirdiğiniz masaları tekrar ayırırsınız. Bu esneklik sayesinde kapasitenizi anlık talebe göre yönetir, kat planınızı sabit bir şemaya hapsetmeden gerçek servise uydurursunuz. Masalar arasındaki her değişiklik plana anında yansıdığı için personeliniz hangi masanın hangi grupla birleştiğini şaşırmaz.",
        bullets: [
          "Büyük gruplar için birkaç dokunuşla masa birleştirme",
          "İhtiyaç bittiğinde birleştirilen masaları yeniden ayırma",
          "Kapasiteyi anlık talebe göre esnetebilme",
          "Her değişikliğin kat planına anında yansıması",
        ],
      },
      {
        title: "Rezervasyonları tek ekranda toplayan yönetim akışı",
        body: "Rezervasyon defterinin karıştığı, iki grubun yanlışlıkla aynı masaya yazıldığı günler geride kalsın. Herkese açık rezervasyon sayfanız sayesinde misafirleriniz kendi başlarına rezervasyon talebi oluşturabilir; siz de gelen tüm rezervasyonları tek bir yönetim ekranından görür, isim ya da tarihle arama yaparak istediğiniz kayda saniyeler içinde ulaşırsınız. Rezerve masalar kat planında ayrı bir durumla işaretlendiği için, dolu bir salonda akşam için tutulan masayı personeliniz yanlışlıkla başka misafire açmaz. Rezervasyon ile masa yerleşimi aynı sistemde konuştuğundan, salonunuzu doluluğa göre önceden planlamak çok daha kolaylaşır.",
        bullets: [
          "Misafirlerin kendi talebini girebildiği herkese açık rezervasyon sayfası",
          "Tüm rezervasyonları tek ekrandan görüntüleme, isim/tarih ile hızlı arama",
          "Rezerve masaların kat planında ayrı durumla işaretlenmesi",
          "Çift rezervasyon ve masa çakışmasını önleyen bütünleşik görünüm",
        ],
      },
    ],
    how: {
      heading: "Masa & Sipariş yönetimi nasıl çalışır?",
      steps: [
        {
          title: "Salonunuzu kat planı editöründe kurun",
          body: "Masalarınızı sürükle-bırak ile yerleştirip restoranınızın gerçek düzenini oluşturun. Salonu 2B veya 3B görünümde düzenler, gerektiğinde masaları birleştirip ayırarak kapasitenizi esnetirsiniz.",
        },
        {
          title: "Masa durumlarını canlı takip edin",
          body: "Servis başladığında kat planı canlı çalışır: boş, dolu ve rezerve masaları renkleriyle tek bakışta görür, salonu bizzat dolaşmadan doluluğunuzu tek ekrandan yönetirsiniz.",
        },
        {
          title: "Rezervasyonları toplayın ve planlayın",
          body: "Herkese açık rezervasyon sayfanızdan gelen talepleri tek yönetim ekranında görün, isim veya tarihle arayıp hızlıca bulun ve rezerve masaları kat planında işaretleyerek çakışmayı baştan önleyin.",
        },
        {
          title: "Misafir taleplerini anında karşılayın",
          body: "Misafirler QR menüden garson veya hesap çağırdığında talep, masa numarasıyla birlikte personelinize düşer; ekibiniz salonu tarayarak vakit kaybetmeden doğru masaya doğru zamanda yönelir.",
        },
      ],
    },
    advantages: [
      "Salonun gerçek yerleşimini birebir yansıtan sürükle-bırak kat planı",
      "Boş, dolu ve rezerve masaları renklerle gösteren canlı durum takibi",
      "Kuşbakışı 2B ve gerçekçi 3B görünüm arasında seçim",
      "Büyük gruplar için masa birleştirme, ihtiyaç bitince yeniden ayırma",
      "Herkese açık rezervasyon sayfası ve tek ekrandan aranabilir rezervasyon yönetimi",
      "QR menüden garson ve hesap çağrısıyla azalan bekleme süreleri",
    ],
    faq: [
      {
        q: "Kat planında masaları kendi salonuma göre düzenleyebilir miyim?",
        a: "Evet. Masaları sürükle-bırak ile istediğiniz yere yerleştirerek restoranınızın gerçek düzenini birebir kurabilirsiniz. Salonu 2B veya 3B görünümde düzenler, düzeniniz değiştikçe planı yeniden şekillendirirsiniz.",
      },
      {
        q: "İki masayı birleştirip sonra tekrar ayırabilir miyim?",
        a: "Evet. Kalabalık bir grup geldiğinde masaları birleştirebilir, grup kalktığında ya da düzen değiştiğinde birleştirdiğiniz masaları yeniden ayırabilirsiniz. Böylece kapasitenizi anlık ihtiyaca göre esnetirsiniz.",
      },
      {
        q: "Rezervasyonları müşteriler mi oluşturuyor, yoksa ben mi giriyorum?",
        a: "İkisi de mümkün. Misafirleriniz herkese açık rezervasyon sayfanızdan kendi taleplerini oluşturabilir; siz de tüm rezervasyonları tek yönetim ekranından görüp isim veya tarihle arayarak yönetebilirsiniz.",
      },
      {
        q: "Misafirler masadan garson veya hesap çağırabiliyor mu?",
        a: "Evet. QR menü üzerinden tek dokunuşla garson çağırabilir ya da hesap isteyebilirler. Talep, masa numarasıyla birlikte personelinize anında iletilir.",
      },
      {
        q: "Masa durumları gerçek zamanlı olarak mı güncelleniyor?",
        a: "Evet. Kat planı canlı çalışır; bir masanın durumu değiştiğinde ekran kendiliğinden güncellenir ve boş, dolu, rezerve masaları renkleriyle tek bakışta ayırt edersiniz.",
      },
    ],
    ctaTitle: "Salonunuzu dijitale taşıyın, her masayı tek ekrandan yönetin",
  },
  "stok-envanter": {
    hero: {
      eyebrow: "Stok & Envanter",
      title:
        "Depodaki her gramın hesabını tutun, mutfaktaki kâr sızıntısını durdurun",
      subtitle:
        "Reçeteyi bir kez tanımlayın; satış gerçekleştikçe malzemeler gramajına kadar, mükerrer düşmeden stoktan insin. Tedarikçiden mal kabulüne, dönem sayımından fire kaydına kadar tüm envanteriniz tek panoda; tahminle değil, izi tutulan gerçek stok hareketleriyle.",
    },
    intro:
      'Restoran ve kafelerde kârın önemli bir kısmı fark edilmeden mutfakta erir: kayan porsiyonlar, deftere geçmeyen fireler, sürekli ertelenen sayımlar, kafada tutulan maliyetler. HummyTummy Stok & Envanter modülü satışı stoğa bağlayarak tam da bu boşluğu kapatır. Her menü ürünü için reçete tanımlarsınız; POS\'ta o ürün satıldığı an, içindeki malzemeler tanımladığınız gramaj kadar stoktan otomatik iner. Tedarikçi kartları, satınalma siparişleri, mal kabulü, dönemsel sayım ve fire kayıtları aynı sistemde birleşir; her biri malzeme hareketi olarak iz bırakır. Böylece \\"elimde ne var, bu tabak bana kaça mal oluyor, kaçak nerede\\" sorularının cevabını hafızanıza ya da tahmine değil, geriye dönük denetlenebilen gerçek stok hareketlerine dayanarak verirsiniz.',
    blocks: [
      {
        title: "Reçeteye bağlı otomatik stok düşümü",
        body: "Modülün kalbi reçetedir. Her menü ürünü için hangi malzemeden ne kadar kullanıldığını bir kez tanımlarsınız; POS'ta o ürün satıldığı anda malzemeler, belirlediğiniz gramaj kadar stoktan kendiliğinden düşer, elle giriş gerekmez. Düşüm idempotent çalışır: aynı adisyon yeniden işlense bile stok yalnızca bir kez azalır, hayalet düşüm oluşmaz. Sipariş iptal veya iade edildiğinde düşen miktar otomatik geri yüklenir. Her işlem 'sipariş düşümü' ya da 'düşüm iptali' olarak malzeme hareketlerine yazılır ve dilediğinizde geriye dönük denetlenebilir.",
        bullets: [
          "Her ürüne malzeme + gramaj reçetesi; satışta stok elle giriş olmadan iner",
          "Aynı adisyon iki kez işlense de stok bir kez azalır (mükerrer düşüm engelli)",
          "Sipariş iptal/iadesinde düşen stok otomatik geri yüklenir",
          "Her hareket sipariş düşümü / iptali olarak iz bırakır, denetlenebilir",
        ],
      },
      {
        title: "Tedarikçi, satınalma ve mal kabulü",
        body: "Stoğun yalnızca azalan tarafını değil, artan tarafını da aynı yerden yönetirsiniz. Tedarikçilerinizi kartlarıyla kaydeder, üzerlerine satınalma siparişi oluşturursunuz. Mal geldiğinde siparişi 'mal kabul' ile karşılarsınız; kabul edilen miktar stoğa otomatik eklenir ve alış fiyatı üzerinden malzeme maliyetiniz güncel kalır. Sipariş bir seferde tam gelmediyse kısmi kabul yapabilir, kalanı sonra karşılayabilirsiniz. Bir siparişi iptal etmeniz gerekirse eklenen stok da geri alınır; böylece kayıtlar her zaman fiili durumla örtüşür.",
        bullets: [
          "Tedarikçi kartları ve iletişim bilgileri tek yerde toplanır",
          "Satınalma siparişi oluşturun, geleni mal kabul ile stoğa alın",
          "Kısmi mal kabulü: eksik gelen siparişin kalanını sonra karşılayın",
          "Mal kabulünde stok otomatik artar, iptalde geri alınır; maliyet alış fiyatına göre güncellenir",
        ],
      },
      {
        title: "Sayım, fire ve kritik stok kontrolü",
        body: "Sistemdeki rakamla raftaki gerçeğin ayrışmaması için üç araç bir arada çalışır. Dönemsel sayımda fiili adedi girersiniz; sistemle aradaki fark otomatik hesaplanıp düzeltme hareketi olarak işlenir, kimin ne zaman saydığı kayıt altında kalır. Bozulan, son kullanma tarihi geçen, hasar gören, hazırlıkta zayi olan ya da fazla üretilen malzemeleri nedeniyle birlikte fire olarak kaydedersiniz; böylece görünmeyen kayıp rakama dönüşür. Belirlediğiniz kritik stok eşiğinin altına inen malzemeler için sistem otomatik uyarır. Hepsini stok panosunda anlık mevcut, hareket geçmişi ve maliyetle tek ekranda izlersiniz.",
        bullets: [
          "Dönemsel sayım: fiili adetle sistem farkı otomatik hesaplanıp düzeltme hareketine yazılır",
          "Fire nedenleri: son kullanma geçmiş, bozulma, hasar, hazırlık firesi, fazla üretim, müşteri iadesi",
          "Kritik eşik altına düşen malzeme için otomatik uyarı",
          "Stok panosunda anlık mevcut, hareketler ve maliyet tek ekranda",
        ],
      },
    ],
    how: {
      heading: "Nasıl çalışır?",
      steps: [
        {
          title: "Malzeme ve tedarikçileri tanımlayın",
          body: "Un, süt, et, sebze... her malzemeyi birimiyle (kilogram, litre, adet, porsiyon) ve kritik stok eşiğiyle sisteme girin, tedarikçilerinizi kartlarıyla kaydedin. Envanterinizin iskeleti bir kez kurulur.",
        },
        {
          title: "Ürün reçetelerini oluşturun",
          body: "Her menü ürününün içindeki malzemeleri gramajıyla eşleyin. Bir kez tanımlarsınız; satışta hangi malzemenin ne kadar düşeceğini bundan sonra sistem bilir.",
        },
        {
          title: "Satış ve alımları olağan akışta yönetin",
          body: "POS'ta satış oldukça reçeteler stoktan düşer; tedarikçiden mal geldikçe satınalma siparişini mal kabulüyle stoğa alırsınız. Günlük akışın dışında ekstra bir işlem gerekmez.",
        },
        {
          title: "Panodan izleyin, sayım ve fireyle kapatın",
          body: "Kritik stok uyarılarını takip edin, dönem sonunda sayımı yapın, fireyi nedeniyle kaydedin. Rakamlar her zaman raftaki gerçeği göstersin.",
        },
      ],
    },
    advantages: [
      "Tahmine değil, izi tutulan gerçek hareketlere dayalı stok",
      "Reçete bazlı otomatik düşümle porsiyon disiplini",
      "Mükerrer düşüm ve hayalet stok riski yok (idempotent)",
      "Fire ve sayım farkları kayıt altında, kaçak görünür hale gelir",
      "Alış fiyatına bağlı güncel malzeme maliyeti ve kâr kontrolü",
      "Çoklu şubede aynı standartla stok takibi",
    ],
    faq: [
      {
        q: "Stok, satış anında otomatik mi düşüyor?",
        a: "Evet. Bir menü ürünü satıldığında reçetesindeki malzemeler, tanımladığınız gramaj kadar stoktan otomatik düşer. Ayrıca elle stok girişi yapmanıza gerek kalmaz.",
      },
      {
        q: "Aynı sipariş iki kez işlenirse stok mükerrer düşer mi?",
        a: "Hayır. Düşüm idempotent çalışır; aynı adisyon tekrar işlense bile stok yalnızca bir kez azalır. Sipariş iptal veya iade edilirse düşen miktar otomatik geri yüklenir.",
      },
      {
        q: "Tedarikçiden gelen malı nasıl stoğa alırım?",
        a: "Tedarikçinize satınalma siparişi oluşturur, mal geldiğinde 'mal kabul' ile karşılarsınız. Kabul edilen miktar stoğa otomatik eklenir; sipariş tam gelmediyse kısmi kabul yapabilir, malzeme maliyeti alış fiyatına göre güncellenir.",
      },
      {
        q: "Fire ve sayım farklarını nasıl yönetiyorum?",
        a: "Bozulan, son kullanma tarihi geçen, hasar gören, hazırlıkta zayi olan ya da fazla üretilen malzemeleri nedeniyle birlikte fire olarak kaydedersiniz. Dönemsel sayımda ise fiili adet ile sistem arasındaki fark otomatik hesaplanıp düzeltme hareketine işlenir.",
      },
      {
        q: "Kritik stok uyarısı var mı?",
        a: "Evet. Her malzeme için kritik stok eşiği belirlersiniz; stok bu seviyenin altına düştüğünde sistem otomatik uyarır. Böylece siparişinizi malzeme tükenmeden zamanında verebilirsiniz.",
      },
    ],
    ctaTitle: "Mutfağınızdaki kâr sızıntısını bugün görünür kılın",
  },
  raporlar: {
    hero: {
      eyebrow: "Raporlar & Analiz",
      title: "İşletmenizi tahminle değil, rakamla yönetin",
      subtitle:
        "Ciro, en çok satan ürünler, ödeme dağılımı, yoğun saatler, stok ve personel performansı tek panelde. Gerçek zamanlı, kural tabanlı ve tek tıkla dışa aktarılabilir.",
    },
    intro:
      'HummyTummy Raporlar & Analiz modülü; POS\'ta kesilen her adisyonu, QR menüden gelen her siparişi ve mutfak ekranına düşen her kalemi tek bir veri havuzunda toplar, bunları anlaşılır grafiklere ve gün sonu özetlerine dönüştürür. Böylece \\"bugün ne kadar sattık, hangi ürün tutuyor, hangi saatte yoğunlaşıyoruz, ödemelerin ne kadarı nakit ne kadarı kart\\" sorularının cevabını akşamı beklemeden, dakikalar içinde ekrandan görürsünüz. Tüm analizler net kural ve eşik tabanlı hesaplamalara dayanır; yani her rakamın nereden geldiği bellidir, kara kutu ya da sürpriz yoktur. Vardiya planlamasından menü kararlarına, stok takibinden gün sonu kapanışına kadar işletmenizin nabzını tek yerden tutarsınız.',
    blocks: [
      {
        title: "Ciro ve satış panelini gerçek zamanlı izleyin",
        body: "Günün ne kadar sattığını görmek için akşam kapanışını beklemenize gerek yok. Panel, satışlar işlendikçe canlı güncellenir; ciro özeti, işlem sayısı ve ortalama adisyon tutarı anlık olarak önünüze gelir. Saat bazlı sipariş yoğunluğuyla salonun hangi dilimlerde dolduğunu, ödeme yöntemi dağılımıyla da nakit, kart ve online tahsilatın oranını tek bakışta okursunuz. Bu veriler vardiya planlamasından mutfak hazırlığına ve masa çevirme hızına kadar günlük operasyonu somut biçimde yönlendirir.",
        bullets: [
          "Ciro özeti: günlük, haftalık ve aylık toplam satış, işlem adedi ve ortalama adisyon tutarı",
          "Saat bazlı sipariş yoğunluğu: hangi saat dilimlerinde yoğunlaştığınızı görün, vardiya ve mutfak hazırlığını buna göre kurun",
          "Ödeme yöntemi dağılımı: nakit, kart ve online (PayTR) tahsilatların oranını tek grafikte karşılaştırın",
          "Gerçek zamanlı panel: satışlar işlendikçe rakamlar akşamı beklemeden canlı güncellenir",
        ],
      },
      {
        title: "Neyin sattığını, neyin stokta eridiğini bilin",
        body: "İyi bir menü kararı sezgiyle değil veriyle alınır. En çok satan ürünler raporu, kalemleri hem adet hem ciro bazında sıralar; menüde neyi öne çıkaracağınıza, hangi ürünün masayı gerçekten döndürdüğüne, hangi kalemin çok satıp az kâr bıraktığına rakamla karar verirsiniz. Envanter raporlarıyla tüketimi ve stok hareketlerini izleyip erken biten kalemleri ve fire eğilimini önceden yakalar, müşteri raporlarıyla da düzenli misafirlerinizin sipariş ve harcama alışkanlığını tanırsınız. Çok şubeli işletmelerde aynı metrikleri şubeler arasında yan yana koyarsınız.",
        bullets: [
          "En çok satan ürünler: adet ve ciro bazında sıralamayla menü kararlarını veriye dayandırın",
          "Envanter/stok raporları: tüketim ve hareketleri izleyerek erken biten kalemleri ve fire eğilimini erkenden görün",
          "Müşteri raporları: sipariş adedi ve harcama davranışıyla düzenli misafirlerinizi tanıyın",
          "Şube bazında karşılaştırma: aynı metrikleri şubeler arasında yan yana inceleyin",
        ],
      },
      {
        title: "Gün sonunu kapatın, ekibi ve salonu ölçün",
        body: "Gün biterken kapanışı tahminle değil dökümle yapın. Gün sonu Z-raporu; günün cirosunu, işlem sayısını ve nakit/kart/online ödeme dökümünü tek bir özet halinde önünüze koyar, kasa uyumunu görmenizi kolaylaştırır. Personel performansı raporuyla kişi bazında açılan adisyonu, işlenen satışı ve ciro katkısını görür; masa doluluk ısı haritasıyla da salonun hangi bölgesinin daha yoğun kullanıldığını anlarsınız. İhtiyaç duyduğunuz her raporu Excel/CSV olarak dışa aktarıp muhasebenize iletebilir ya da kendi analizinizde kullanabilirsiniz.",
        bullets: [
          "Gün sonu Z-raporu: kapanışta günün cirosunu, işlem sayısını ve ödeme dökümünü tek özette alın",
          "Personel performansı: kişi bazında açılan adisyon, işlenen satış ve ciro katkısı",
          "Masa doluluk ısı haritası: kenar kamera cihazlarıyla salonun yoğun bölgelerini görselleştirin (uyumlu kamera cihazı gerektirir)",
          "Excel/CSV dışa aktarım: her raporu tek tıkla indirip muhasebe veya kendi analizinizde kullanın",
        ],
      },
    ],
    how: {
      heading: "Raporlar & Analiz nasıl çalışır?",
      steps: [
        {
          title: "Veriler otomatik toplanır",
          body: "POS'ta kesilen adisyonlar, QR menüden gelen siparişler ve mutfak ekranına düşen kalemler arka planda tek bir veri havuzunda birleşir. Elle giriş yapmanıza ya da ayrı bir tablo tutmanıza gerek kalmaz.",
        },
        {
          title: "Tarih ve şube seçin",
          body: "Paneli günlük, haftalık veya aylık aralıkla ve şube bazında filtreleyin; işletmenin genel toplamını ya da tek bir şubeyi anında karşılaştırın.",
        },
        {
          title: "Kural tabanlı analizle görselleştirin",
          body: "Eşik ve kural tabanlı hesaplamalar rakamları grafiklere, sıralamalara ve dağılımlara dönüştürür. Yapay zeka tahmini değildir; her sayının nasıl çıktığı bellidir, hesap şeffaftır.",
        },
        {
          title: "Dışa aktarın veya gün sonu alın",
          body: "İncelediğiniz raporu Excel/CSV olarak indirin ya da kapanışta gün sonu Z-raporunu tek tıkla üretip günü net biçimde kapatın.",
        },
      ],
    },
    advantages: [
      "Gerçek zamanlı panel: satışlar işlendikçe rakamlar canlı güncellenir",
      "Kural ve eşik tabanlı, şeffaf hesap; kara kutu değil",
      "Çoklu şubeyi tek ekrandan karşılaştırma",
      "Ciro, ürün, ödeme, envanter ve personel raporlarını Excel/CSV ile dışa aktarma",
      "Tek tıkla gün sonu Z-raporu",
      "Masa doluluk ısı haritasıyla salon verimini ölçme (uyumlu kamera cihazıyla)",
    ],
    faq: [
      {
        q: "Raporlar gerçek zamanlı mı, yoksa ertesi gün mü oluşuyor?",
        a: "Panel gerçek zamanlıdır; POS, QR menü ve mutfak ekranından gelen satışlar işlendikçe ciro ve grafikler canlı güncellenir. Gün sonu Z-raporunu ise kapanışta tek tıkla alırsınız.",
      },
      {
        q: "Analizlerde yapay zeka mı kullanılıyor?",
        a: "Hayır. Tüm raporlar kural ve eşik tabanlı hesaplamalara dayanır. Bir rakamın nasıl çıktığı bellidir; tahmine dayalı bir kara kutu yoktur.",
      },
      {
        q: "Birden çok şubem var, hepsini ayrı ayrı mı izlemem gerekiyor?",
        a: "Hayır. Aynı metrikleri şube bazında filtreleyebilir veya şubeleri yan yana karşılaştırabilirsiniz. İşletmenin genel toplamını da tek ekranda görürsünüz.",
      },
      {
        q: "Raporları dışa aktarabilir miyim?",
        a: "Evet. Ciro, ürün, ödeme, envanter ve personel raporlarını Excel/CSV olarak indirip muhasebenize iletebilir ya da kendi analizinizde kullanabilirsiniz.",
      },
      {
        q: "Masa doluluk ısı haritası nasıl çalışıyor?",
        a: "Salona yerleştirilen kenar kamera cihazlarından gelen doluluk verisiyle hangi bölgelerin daha yoğun kullanıldığını görselleştirir. Bu özellik için uyumlu bir kamera cihazı gerekir.",
      },
    ],
    ctaTitle: "İşletmenizi rakamlarla yönetmeye bugün başlayın",
  },
  "coklu-sube": {
    hero: {
      eyebrow: "Çoklu Şube Yönetimi",
      title: "Şube sayınız artarken kontrol elinizden kaçmasın",
      subtitle:
        "İster iki şubeyle büyümeye başlayın, ister bir zincir işletin; menüden yetkilere, cihazlardan raporlara kadar her şubeyi tek hesaptan ve tek buluttan yönetin. Her şubenin kendi ekibi, kendi cihazları ve kendi rakamları tek çatı altında toplanır — hepsi görünür kalır, hiçbiri birbirine karışmaz.",
    },
    intro:
      "Bir şube açmak zordur; ikincisini, üçüncüsünü aynı standartla yönetmek daha da zordur. Her şube için ayrı hesap, ayrı Excel ve ayrı WhatsApp grubu derken hangi şubede ne olduğunu takip etmek imkânsız hâle gelir. HummyTummy'nin Çoklu Şube modülü tam da bu dağınıklığı ortadan kaldırmak için tasarlandı: tüm şubeleriniz tek hesabın altında toplanır, her şube kendi menüsünü, ekibini, cihazlarını ve raporlarını taşır; siz ise yönetici panelinden hepsine tek bakışta hâkim olursunuz. İşletme sahibi olarak bütün şubeleri görürsünüz; sahadaki garson, mutfak ve kurye yalnızca kendi şubesini görür. Böylece büyürken standardınızı korur, verileri karıştırmaz ve yeni şube açtığınızda aynı düzeni dakikalar içinde yeniden kurarsınız.",
    blocks: [
      {
        title: "Tek hesap, şube bazlı yetki, menü ve raporlama",
        body: "Bütün şubeleriniz aynı hesabın altında yaşar ama verileri birbirine karışmaz. Her şubenin kendi menüsü, kendi fiyatlandırması ve kendi ekibi vardır; yetkiler hem role hem de şubeye göre ayrılır. Sahip ve yönetici tüm şubeleri görüp aralarında tek tıkla geçerken; garson, mutfak ve kurye yalnızca bağlı olduğu şubenin ekranıyla çalışır. Şube kısıtlı bir müdür ise yalnızca kendisine atanan şubeleri görür, diğerlerinin cirosuna ya da personeline erişemez. Bu ayrım hem veriyi güvende tutar hem de her yöneticinin yalnızca kendi işine odaklanmasını sağlar. Ciroyu, sipariş adedini ve şube performansını hem tek tek hem de şubeler arası karşılaştırmalı okursunuz.",
        bullets: [
          "Sahip ve yönetici tüm şubeleri görür; garson, mutfak, kurye ve şube müdürü yalnızca yetkili olduğu şubeye erişir",
          "Her şube kendi menüsünü, fiyatlandırmasını ve personel kadrosunu bağımsız taşır",
          "Şube bazında ciro, sipariş adedi ve performans; şubeleri yan yana karşılaştıran raporlar",
          "Şubeler arası geçiş tek tık — çıkış yapıp yeniden giriş yapmaya gerek yok",
        ],
      },
      {
        title: "Şube bazlı cihaz ve ağ merkezi: Cihazlar, topoloji ve sağlık",
        body: "Her şubenin kendi Cihazlar merkezi vardır; o şubeye ait tüm donanımı tek ekrandan görürsünüz. Şube içi ağ topolojisi görsel olarak çıkarılır: yerel köprü ajanları, her köprünün arkasındaki cihazlar ve buluta doğrudan bağlı cihazlar aynı haritada belirir; hangi yazıcının hangi köprüye bağlı olduğunu bir bakışta anlarsınız. Cihazlar düzenli aralıklarla (yaklaşık 10 saniyede bir) sinyal — heartbeat — gönderir; sinyali kesilen cihaz kısa bir bekleme penceresinin ardından otomatik olarak 'çevrimdışı' işaretlenir. Böylece bir fiş yazıcısı ya da ekran sustuğunda haberiniz, müşteri masaya oturmadan olur. Her şubenin bir sağlık skoru vardır: renkli durum rozeti ve puanıyla hangi şubede sorun olduğunu tek bakışta görür, sahaya gitmeden önce nereye bakacağınızı bilirsiniz.",
        bullets: [
          "Şube içi ağ topolojisi: köprü ajanları, arkasındaki cihazlar ve buluta doğrudan bağlı cihazlar tek haritada",
          "Canlı durum: düzenli heartbeat ile çevrimiçi/çevrimdışı takibi; sinyali kesilen cihaz otomatik işaretlenir",
          "Şube sağlık skoru: renkli durum rozeti ve puanla sorunlu şubeyi anında tespit",
          "ESC/POS fiş yazıcıları tanımlanır ve doğru şubeyle eşlenir",
        ],
      },
      {
        title: "Yerel köprü ajanı ve masaüstü kurulum uygulaması",
        body: "Şubelerinizdeki fiş yazıcıları ve diğer cihazlar, o şubede çalışan yerel köprü ajanı üzerinden buluta bağlanır. Sipariş fişleri şube içi ağdan yazıcıya iletildiği için basım yereldir ve hızlıdır; internet bir an yavaşlasa bile fişler şube ağında akmaya devam eder. Kurulumu ise masaüstü uygulaması üstlenir: Windows, macOS ve Linux üzerinde çalışan uygulamayla cihazlarınızı tek seferlik eşleme koduyla güvenli biçimde bağlar, provizyonu dakikalar içinde tamamlarsınız. Yeni bir şube açtığınızda aynı adımları izler, kurulumu bir şablon gibi çoğaltırsınız — her şubede sıfırdan uğraşmaz, aynı düzeni tekrar tekrar kurarsınız.",
        bullets: [
          "Yerel köprü ajanı sipariş fişlerini şube içi ağdan ESC/POS yazıcıya iletir",
          "Masaüstü kurulum uygulaması Windows, macOS ve Linux'ta çalışır",
          "Cihazlar tek seferlik eşleme koduyla güvenli şekilde bağlanır",
          "Yeni şube açılışında aynı kurulumu tekrarlayarak düzeni hızla çoğaltın",
        ],
      },
    ],
    how: {
      heading: "Çoklu şube kurulumu nasıl çalışır?",
      steps: [
        {
          title: "Şubelerinizi tanımlayın",
          body: "Tek hesabınızın altında her şubeyi adı, konumu ve kendi menüsüyle oluşturun. Her yeni şube, kendi cirosu ve cihazlarıyla anında panele eklenir.",
        },
        {
          title: "Ekibi ve yetkileri şubeye atayın",
          body: "Personeli rolüne göre (garson, mutfak, kurye, şube müdürü) ilgili şubeye bağlayın. Saha ekibi yalnızca kendi şubesini görür; yönetici ve sahip tüm şubelere erişir.",
        },
        {
          title: "Cihazları masaüstü uygulamayla eşleyin",
          body: "Masaüstü kurulum uygulamasını şubeye kurun, yerel köprü ajanını başlatın ve fiş yazıcılarını tek seferlik eşleme koduyla bağlayın. Cihazlar birkaç dakikada devreye girer.",
        },
        {
          title: "Tek panelden yönetin ve raporlayın",
          body: "Artık tüm şubeleri tek ekrandan izler, cihaz sağlığını canlı takip eder ve şube bazlı raporları karşılaştırmalı okursunuz. Şubeler arası geçiş yalnızca tek tık.",
        },
      ],
    },
    advantages: [
      "Tüm şubeler tek hesap ve tek panelde — dağınık, kopuk kurulumlara son",
      "Şube bazlı rol ve yetki sayesinde ekipler ve veriler birbirine karışmaz",
      "Şube içi ağ topolojisi ve canlı cihaz sağlığı tek ekranda görünür",
      "Sinyali kesilen yazıcı veya ekran otomatik 'çevrimdışı' işaretlenir — sürprizi masada yaşamazsınız",
      "Yerel köprü ajanıyla şube içi ağdan hızlı ve kesintiye dayanıklı fiş basımı",
      "Masaüstü kurulum uygulamasıyla yeni şubeyi dakikalar içinde ayağa kaldırın",
    ],
    faq: [
      {
        q: "Kaç şube ekleyebilirim?",
        a: "Tüm şubelerinizi tek hesabın altında yönetebilirsiniz. Şube sayısı abonelik planınızın kapsamına göre belirlenir; işletmeniz büyüdükçe yeni şubeleri aynı panele eklemeye devam edersiniz.",
      },
      {
        q: "Bir şubedeki personel diğer şubelerin verilerini görebilir mi?",
        a: "Hayır. Garson, mutfak ve kurye yalnızca bağlı olduğu şubeyi görür; şube kısıtlı bir müdür de yalnızca kendisine atanan şubelere erişir. Tüm şubeleri görüp aralarında geçiş yapma yetkisi yalnızca sahip ve yöneticidedir.",
      },
      {
        q: "Bir şubedeki cihazların çevrimiçi olup olmadığını nasıl anlarım?",
        a: "Her şubenin Cihazlar merkezinden durumu canlı izlersiniz. Cihazlar düzenli aralıklarla sinyal gönderir; sinyali kesilen cihaz otomatik olarak 'çevrimdışı' işaretlenir ve şubenin sağlık skoruna yansır.",
      },
      {
        q: "Yeni bir şube açarken ne yapmam gerekir?",
        a: "Şubeyi panelde tanımlayın, ekibi ve yetkileri atayın, ardından masaüstü kurulum uygulamasıyla cihazları eşleyin. Aynı adımları tekrarlayarak kurulumu her yeni şubede hızla çoğaltırsınız.",
      },
      {
        q: "Her şubede menü aynı olmak zorunda mı?",
        a: "Hayır. Her şube kendi menüsünü ve fiyatlandırmasını bağımsız taşıyabilir; şubeye özel ürün ve fiyat tanımlayabilir, dilerseniz şubeler arasında benzer bir menü de yürütebilirsiniz.",
      },
    ],
    ctaTitle: "Tüm şubelerinizi tek panelden yönetmeye bugün başlayın",
  },
  entegrasyonlar: {
    hero: {
      eyebrow: "Entegrasyonlar",
      title: "Tüm sipariş kanallarınız ve sistemleriniz tek panelde birleşsin",
      subtitle:
        "Yemeksepeti, Getir, Trendyol Yemek ve Migros Yemek'ten gelen paket siparişler, e-Fatura entegratörünüz, partner ekranlarınız ve online tahsilat aynı çatı altında. Ayrı tabletler, elle yeniden giriş ve dağınık sistemler yerine tek, düzenli bir akış.",
    },
    intro:
      "Bir restoran artık tek bir kanaldan yönetilmiyor: paket siparişler dört ayrı teslimat platformundan geliyor, muhasebe e-fatura entegratörünüz üzerinden yürüyor, online ödemeler ayrı bir kanaldan tahsil ediliyor. HummyTummy Entegrasyonlar modülü bu dağınık akışı tek yerde toplar. Her platformun kendi tabletini önünde personel koşturmak, gelen siparişi elle POS'a yeniden girmek ya da her sistem için ayrı takip tutmak yerine; siparişler otomatik olarak sisteme düşer, doğru şubeye yönlendirilir ve mutfak ekranınıza işlenir. Teslimat platformlarını, e-Fatura/e-Arşiv sağlayıcılarını, partner ekranlarını ve PayTR online ödemeyi tek panelden bağlar, açar-kapatır ve izlersiniz.",
    blocks: [
      {
        title: "Dört teslimat platformu, tek sipariş paneli",
        body: "Yemeksepeti, Getir, Trendyol Yemek ve Migros Yemek'in tümü gerçek üretim adaptörleriyle entegredir. Her platformun ayrı tabletine bakıp siparişi elle adisyona geçirmek yerine, dört kanaldan gelen siparişler HummyTummy'nin tek paneline akar; otomatik olarak sisteme düşer ve mutfak ekranına işlenir. Çok şubeli işletmelerde her şube kendi platform hesaplarıyla eşleşir, böylece gelen her sipariş ait olduğu şubenin mutfağına yönlendirilir. Entegrasyonu canlıya almadan önce sandbox simülatörüyle tüm akışı gerçek sipariş göndermeden deneyebilir, her şeyin doğru çalıştığını görebilirsiniz.",
        bullets: [
          "Yemeksepeti, Getir, Trendyol Yemek ve Migros Yemek için gerçek üretim adaptörleri",
          "Dört platformun siparişi tek panelde birleşir; elle yeniden giriş yok",
          "Çok şubeli eşleştirme: her sipariş doğru şubenin mutfağına düşer",
          "Sandbox simülatörüyle canlıya geçmeden uçtan uca test",
        ],
      },
      {
        title: "e-Fatura / e-Arşiv: mevcut entegratörünüz üzerinden",
        body: "HummyTummy; Paraşüt, Foriba ve Logo ile e-Fatura / e-Arşiv entegrasyon altyapısına sahiptir. Turnkey bir kutu değildir: hangi entegratörle çalıştığınızı ve erişim bilgilerinizi sağlayıcı olarak tanımladığınızda, ödemesi tamamlanmış siparişler için belge oluşturma akışı devreye girer. Entegrasyon güvenlik gereği varsayılan olarak kapalı gelir; siz sağlayıcınızı bağlayana kadar hiçbir belge üretilmez, böylece yanlış yapılandırmadan kaynaklı hatalı fatura riski olmaz. Bu sayede muhasebe tarafını zaten kullandığınız e-fatura entegratörünüz üzerinden yürütür, ikinci bir sisteme veri kopyalamaktan kurtulursunuz.",
        bullets: [
          "Paraşüt, Foriba ve Logo için hazır entegrasyon altyapısı",
          "Belge akışı, ödemesi tamamlanmış siparişler için çalışır",
          "Varsayılan kapalı: sağlayıcı tanımlanana kadar belge üretilmez",
          "Muhasebeyi mevcut entegratörünüz üzerinden yürütün, çift veri girişi olmaz",
        ],
      },
      {
        title: "Partner Ekran API'si ve PayTR online tahsilat",
        body: "Masa tabletlerini, self-servis ekranları ya da üçüncü taraf gösterim cihazlarını sisteme bağlamak için kapsamlı bir Partner Ekran API'si sunulur. Her ekran, ana API anahtarınızdan türetilen ve yalnızca ihtiyaç duyduğu yetkileri (scope) taşıyan kendi oturum token'ıyla çalışır. Bir ekranın token'ı asla anahtarın sahip olmadığı bir yetkiyi kazanamaz; böylece salonunuzdaki her cihaz sınırlı ve denetlenebilir bir erişimle çalışır. Online tahsilat tarafında ise PayTR entegrasyonu devrededir: müşteri ödemesini çevrimiçi alırsınız ve tahsilat onaylanmadan işlem tamamlanmaz.",
        bullets: [
          "Partner Ekran API'si ile masa tabletlerini ve 3. taraf ekranları bağlayın",
          "Ekran başına kapsam (scope) sınırlı token, her zaman ana anahtarın alt kümesi",
          "Bir ekran, anahtarın taşımadığı bir yetkiyi asla kazanamaz",
          "PayTR ile online tahsilat; ödeme onaylanmadan işlem tamamlanmaz",
        ],
      },
    ],
    how: {
      heading: "Entegrasyonlar nasıl çalışır?",
      steps: [
        {
          title: "Bağlayın",
          body: "Panelden çalışmak istediğiniz teslimat platformunu ya da e-fatura sağlayıcısını seçip erişim bilgilerinizi girin. Çok şubeli iseniz her şubeyi kendi platform hesabıyla eşleştirin.",
        },
        {
          title: "Test edin",
          body: "Teslimat entegrasyonlarını sandbox simülatörüyle deneyin. Gerçek sipariş göndermeden, siparişin doğru şubeye ve mutfak ekranına düştüğünü görün.",
        },
        {
          title: "Canlıya alın",
          body: "Entegrasyonu açtığınızda siparişler tek panele akmaya başlar; sağlayıcınız tanımlıysa ödemesi tamamlanmış siparişler için belge akışı devreye girer.",
        },
        {
          title: "Yönetin",
          body: "Tüm platformları ve ekranları tek yerden izleyin; gerektiğinde bir entegrasyonu kapatın ya da ekran token'larının yetkilerini güncelleyin.",
        },
      ],
    },
    advantages: [
      "Dört teslimat platformu tek panelde, tablet karmaşasına son",
      "Çok şubeli mimari: her sipariş otomatik olarak doğru şubeye",
      "Sandbox simülatörüyle canlıya geçmeden risksiz test",
      "e-Fatura / e-Arşiv için Paraşüt, Foriba ve Logo altyapısı",
      "Kapsam sınırlı ekran token'larıyla güvenli üçüncü taraf erişimi",
      "PayTR ile online tahsilat, ödeme onayına bağlı işlem",
    ],
    faq: [
      {
        q: "Hangi teslimat platformları destekleniyor?",
        a: "Yemeksepeti, Getir, Trendyol Yemek ve Migros Yemek. Dördü de gerçek üretim adaptörleriyle çalışır ve gelen siparişler tek panelde birleşir.",
      },
      {
        q: "Siparişleri elle POS'a yeniden girmem gerekir mi?",
        a: "Hayır. Bağlı platformlardan gelen siparişler otomatik olarak sisteme düşer ve mutfak ekranına işlenir; ayrı tabletlerde takip edip yeniden yazmanıza gerek kalmaz.",
      },
      {
        q: "e-Fatura otomatik mi kesiliyor?",
        a: "Turnkey değildir; önce Paraşüt, Foriba veya Logo'dan birini sağlayıcı olarak tanımlamanız gerekir. Tanımladığınızda ödemesi tamamlanmış siparişler için belge akışı çalışır. Entegrasyon varsayılan kapalı gelir, siz bağlayana kadar hiçbir belge üretilmez.",
      },
      {
        q: "Çok şubeli işletmede nasıl çalışıyor?",
        a: "Her şube kendi platform hesaplarıyla eşlenir. Gelen sipariş otomatik olarak ait olduğu şubenin paneline ve mutfak ekranına yönlendirilir.",
      },
      {
        q: "Canlıya geçmeden test edebilir miyim?",
        a: "Evet. Teslimat entegrasyonları için sandbox simülatörü sayesinde gerçek sipariş göndermeden tüm akışı deneyebilir, canlıya güvenle geçersiniz.",
      },
    ],
    ctaTitle:
      "Tüm sipariş kanallarınızı ve sistemlerinizi tek çatı altında toplayın",
  },
};
