// Deep-dive content for the module sub-pages (/ozellikler/:slug). The rich TR
// copy (hero/intro/blocks/how/advantages/faq) is authored + honesty-verified
// separately; the image + related-module wiring lives here (CONTENT_META). A
// fallback derives a minimal page from the base module so a page never breaks
// even if copy is missing for a slug.

import type { ImgKey } from "./images";
import { MODULES, moduleBySlug } from "./modules";
import { GENERATED_CONTENT } from "./moduleContent.generated";

export interface ContentBlock {
  title: string;
  body: string;
  bullets: string[];
}

export interface HowStep {
  title: string;
  body: string;
}

export interface ModuleCopy {
  hero: { eyebrow: string; title: string; subtitle: string };
  intro: string;
  blocks: ContentBlock[];
  how: { heading: string; steps: HowStep[] };
  advantages: string[];
  faq: { q: string; a: string }[];
  ctaTitle: string;
}

export interface ModuleMeta {
  heroImage: ImgKey;
  blockImages: ImgKey[];
  related: string[];
}

// Image + related-module assignments (chosen by real image content).
export const CONTENT_META: Record<string, ModuleMeta> = {
  "qr-menu": {
    heroImage: "qrStand",
    blockImages: ["heroTablet", "mascotServe"],
    related: ["pos-odeme", "masa-siparis", "entegrasyonlar"],
  },
  "pos-odeme": {
    heroImage: "posChef",
    blockImages: ["posTerminal", "reportPhone"],
    related: ["qr-menu", "mutfak-ekrani-kds", "raporlar"],
  },
  "mutfak-ekrani-kds": {
    heroImage: "kdsChef",
    blockImages: ["kdsCooking", "dioramaInterior"],
    related: ["pos-odeme", "masa-siparis", "stok-envanter"],
  },
  "masa-siparis": {
    heroImage: "dioramaInterior",
    blockImages: ["dioramaBuilding", "mascotServe"],
    related: ["qr-menu", "pos-odeme", "coklu-sube"],
  },
  "stok-envanter": {
    heroImage: "chartIcon",
    blockImages: ["analytics", "posTerminal"],
    related: ["raporlar", "pos-odeme", "entegrasyonlar"],
  },
  raporlar: {
    heroImage: "reportPhone",
    blockImages: ["analytics", "chartIcon"],
    related: ["stok-envanter", "coklu-sube", "pos-odeme"],
  },
  "coklu-sube": {
    heroImage: "dioramaBuilding",
    blockImages: ["cloudNetwork", "cloudServers"],
    related: ["raporlar", "masa-siparis", "entegrasyonlar"],
  },
  entegrasyonlar: {
    heroImage: "deliveryScooter",
    blockImages: ["deliveryCity", "cloudNetwork"],
    related: ["qr-menu", "pos-odeme", "coklu-sube"],
  },
};

// Rich, honesty-verified copy per module — generated by the deep-dive authoring
// pass (module-deepdive-copy workflow) into moduleContent.generated.ts.
export const MODULE_CONTENT: Record<string, ModuleCopy> = GENERATED_CONTENT;

/** Content for a slug, with a graceful fallback built from the base module. */
export function getModuleCopy(slug: string): ModuleCopy | null {
  if (MODULE_CONTENT[slug]) return MODULE_CONTENT[slug];
  const m = moduleBySlug(slug);
  if (!m) return null;
  return {
    hero: { eyebrow: m.title, title: m.tagline, subtitle: m.bullets[0] },
    intro: m.bullets.join(" "),
    blocks: [{ title: m.title, body: m.tagline, bullets: m.bullets }],
    how: { heading: "Nasıl çalışır?", steps: [] },
    advantages: m.bullets,
    faq: [],
    ctaTitle: "Bugün ücretsiz deneyin",
  };
}

export const MODULE_SLUGS = MODULES.map((m) => m.slug);
