// AUTO-GENERATED by the modules-sectors-copy workflow. Rich, honesty-verified TR
// sector copy for /cozumler/:slug. Do not edit by hand — regenerate.
import type { SectorCopy } from "./sectorContent";

export const GENERATED_SECTORS: Record<string, SectorCopy> = {
  restoran: {
    hero: {
      eyebrow: "Restoran Yönetim Sistemi",
      title: "Masalarınız daha hızlı dönsün, mutfağınız hiç şaşırmasın",
      subtitle:
        "Kat planından POS'a, şube mutfak ekranından stok-reçeteye kadar restoranınızın tüm operasyonu tek sistemde. Siparişi masanın başında alın, saniyede mutfağa düşürün, servisi geciktirmeyin.",
    },
    intro:
      "Akşam servisinde salon dolduğunda her saniye ciroya dokunur. Garsonun sipariş için mutfağa koşturması, kaybolan kağıt adisyonlar, yanlış giden tabaklar ve boşta bekleyen masalar hem gününüzü yavaşlatır hem misafirin keyfini kaçırır. HummyTummy; kat planını, POS'u, şube mutfak ekranını, QR menüyü, stok-reçeteyi, rezervasyonu ve raporları tek panelde birleştirir. Siparişi masanın başında tabletten ya da kasadan alırsınız, sipariş o anda şubenizin mutfak ekranına kağıtsız düşer, hazır olan yemek vakit kaybetmeden servise çıkar. İster tek şube çalıştırın ister birden çok şubeyi aynı hesaptan yönetin, akış hep aynı hız ve düzende işler.",
    blocks: [
      {
        title: "Kat planını birebir kurun, masaları tek bakışta çevirin",
        body: "Salonunuzu, terasınızı ve ayrı bölümlerinizi sürükle-bırak ile gerçek yerleşimine göre çizersiniz. Her masanın boş, dolu ya da rezerve durumunu renklerden anında görür; hangi masanın hesabının açık, hangisinin servise hazır olduğunu tek ekrandan takip edersiniz. Kalabalık masaları hızla çözmek, boşalanı anında sıradaki misafire açmak masa çevirme hızınızı doğrudan artırır.",
        bullets: [
          "Salon, teras ve bölümlerinizi sürükle-bırak ile birebir çizin; her masanın doluluk, rezervasyon ve adisyon durumunu renklerden anında okuyun",
          "Masa birleştirme, masa taşıma ve hesabı kişi ya da ürün bazında bölme ile kalabalık masaları saniyeler içinde yönetin",
          "Adisyonu masada açık tutun, ek sipariş geldikçe ekleyin, hesap istendiğinde tek dokunuşla kapatın",
          "Boşalan masayı anında yeniden açın, bekleyen misafiri boş masayla oyalamayın",
        ],
      },
      {
        title: "Sipariş masadan mutfağa saniyede düşsün",
        body: "POS'tan ya da garsonun tabletinden alınan sipariş, kağıda ve mutfağa koşturmaya gerek kalmadan şubenizin mutfak ekranına anında iletilir. Mutfak siparişi görür, hazırlığa başlar ve bittiğinde işaretler; garson hangi masanın yemeğinin çıktığını ekrandan izler. Salon ile mutfak aynı ritimde çalışınca yanlış giden ve unutulan tabak sayısı düşer.",
        bullets: [
          "Alınan sipariş kağıtsız olarak şubenizin mutfak ekranına anında düşer, garson mutfağa koşmak zorunda kalmaz",
          "Mutfak siparişi hazırlanıyor ve hazır olarak işaretler; garson hangi masanın hangi yemeğinin çıktığını ekrandan görür",
          "Ürün notları, porsiyon ve varyasyonlar (az pişmiş, sossuz, ekstra malzeme) siparişle birlikte mutfağa iletilir",
          "İptal, ikram ve düzeltme işlemleri yetki bazlı yapılır; hesap her adımda tutarlı kalır",
        ],
      },
      {
        title: "Reçeteyle maliyeti, raporla kârı elinizde tutun",
        body: "Her yemeğin reçetesini tanımladığınızda satış gerçekleştikçe kullanılan malzeme stoktan otomatik düşülür, azalan ürünler için uyarı alırsınız. Tabak maliyetini ve kâr marjını ürün bazında görür, fiyatlarınızı tahminle değil veriyle belirlersiniz. Ciro, yoğun saatler, en çok satan ürünler ve garson performansı kural tabanlı raporlarla önünüze gelir; kararı hisle değil rakamla verirsiniz.",
        bullets: [
          "Her yemeğin reçetesini tanımlayın; satış oldukça malzeme stoğu otomatik düşülsün, azalan ürünlerde uyarı gelsin",
          "Tabak maliyetini ve kâr marjını ürün bazında görün, fiyatlandırmayı veriyle netleştirin",
          "Günün ve saatin cirosu, en çok satan ürünler, masa doluluğu ve garson performansı kural tabanlı raporlarla önünüzde",
          "QR menüyü masaya koyduğunuz karekodla paylaşın; menü içeriğini ve fiyatları panelden güncelleyin, değişiklik anında yansısın",
        ],
      },
    ],
    why: [
      "Kat planı, POS, şube mutfak ekranı, QR menü, stok-reçete, rezervasyon ve raporlama ayrı ayrı programlar değil, tek panelde toplanır",
      "Birden çok şubenizi tek hesaptan yönetin; her şubenin menüsünü, stoğunu ve cirosunu ayrı görün ya da topluca izleyin",
      "Masa rezervasyonlarını kat planı üzerinden alın; dolu, ayrılmış ve rezerve masaları karıştırmadan planlayın",
      "Nakit, kart ve online ödeme tiplerini hesapta kayıt altına alın; online tahsilatı PayTR altyapısıyla toplayın",
      "Garson, kasiyer, mutfak ve yönetici rolleriyle her ekip üyesi yalnızca kendi işini görür, hesap güvende kalır",
      "Tarayıcıdan çalışan bulut sistem; ağır kurulum yükü olmadan salonda, kasada ve mutfakta aynı anda açık",
    ],
    faq: [
      {
        q: "Tek programda hem POS hem mutfak ekranı hem kat planı var mı?",
        a: "Evet. HummyTummy tek sistemde kat planı, POS, şube mutfak ekranı, QR menü, stok-reçete, rezervasyon ve raporları birleştirir. Salon, kasa ve mutfak için ayrı ayrı yazılım kullanmanıza gerek kalmaz.",
      },
      {
        q: "Mutfak ekranı istasyon istasyon mu çalışıyor?",
        a: "Her şube için tek mutfak ekranı sunuyoruz. Siparişler bu ekrana kağıtsız düşer, mutfak hazırlanıyor ve hazır durumlarını işaretler, garson servise çıkacak tabağı ekrandan takip eder.",
      },
      {
        q: "Birden fazla şubem var, hepsini tek yerden yönetebilir miyim?",
        a: "Evet. Şubelerinizi tek hesaptan yönetir, her şubenin menüsünü, stoğunu ve raporunu ayrı ayrı görebilir ya da tümüne toplu bakabilirsiniz.",
      },
      {
        q: "Online ödeme alabiliyor muyum?",
        a: "Online tahsilatı PayTR altyapısıyla alırsınız. Nakit ve kart gibi ödeme tiplerini de hesapta kayıt altına alarak gün sonunda tutarlı bir kasa raporu görürsünüz.",
      },
      {
        q: "QR menü var mı, menüyü nasıl güncelliyorum?",
        a: "Masaya koyduğunuz karekodla misafir menüyü kendi telefonundan görür. Menü içeriğini ve fiyatları yönetim panelinden güncellersiniz, değişiklik anında yansır. Yönetim arayüzü beş dilde çalışır.",
      },
    ],
    ctaTitle:
      "Restoranınızı salondan mutfağa tek panelden yönetmeye bugün başlayın",
  },
  kafe: {
    blocks: [
      {
        title: "Barista sipariş beklemesin, masa kendi siparişini versin",
        body: "Yoğun saatte en çok vakit; sipariş almakla, fişi mutfağa iletmekle ve kasada kuyruğu eritmekle kaybolur. HummyTummy masadaki QR menüden gelen siparişi doğrudan şubenizin mutfak ekranına düşürür, dokunmatik POS'ta ödemeyi hızlandırır. Barista sipariş almak için masaya koşmaz, garson elindeki adisyonu kaybetmez; herkes ne hazırlanacağını aynı ekrandan görür.",
        bullets: [
          "Masadaki QR'dan verilen sipariş anında şubenizin mutfak ekranına düşer; el yazısı fiş ve kaybolan adisyon derdi biter.",
          "Dokunmatik POS'ta sık satılan kahve, tatlı ve menüleri tek dokunuşla ekleyin, yoğun saatte saniye kazanın.",
          "Sipariş hazırlanıyor mu, hazır mı ekranda görünür; hangi masanın neyi beklediği net belli olur.",
          "Online ödemeyi PayTR ile tahsil edin; nakit veya kartla ödeyen müşterinin ödemesini kasada tek dokunuşla adisyona işleyin.",
        ],
      },
      {
        title: "Sabah kahvesine gelen müşteri, yarın yine sizde olsun",
        body: "Kafe işi tekrar eden müşteriyle büyür. Her gün aynı kahveyi içen müşterinizi hatırlamak ve ona bir sebep vermek, tek seferlik bir satıştan çok daha değerlidir. HummyTummy'nin puan ve kademe tabanlı sadakat sistemiyle sık gelen müşterinizi tanır, ona özel avantaj tanımlar ve geri dönüşünü artırırsınız.",
        bullets: [
          "Her harcamada puan biriktirin, belirlediğiniz kademelerde sadık müşterinize otomatik avantaj tanımlayın.",
          "Müşteri telefon numarasıyla tanınsın; kim ne sıklıkla geliyor panelde görünür olsun.",
          "Biriken puanı indirim ya da ödüle çevirerek müşterinizi yeniden masaya oturtun.",
        ],
      },
      {
        title:
          "Fincan başına maliyeti bilin, teslimat siparişini tek ekrandan yönetin",
        body: "Süt, çekirdek, şurup derken maliyet sessizce sızar; teslimat siparişleri de her platformun ayrı tabletinde beklemenizi ister. HummyTummy stok tüketimini reçeteye bağlar, teslimat platformlarını tek panele toplar ve kural/eşik tabanlı raporlarla neyin işlediğini, neyin kar ettiğini gösterir.",
        bullets: [
          "Süt, çekirdek, şurup gibi malzemelerin stoğunu takip edin; reçeteye bağlı tüketimle kalan miktarı görün.",
          "Yemeksepeti, Getir, Trendyol ve Migros siparişleri tek panele düşsün; her platform için ayrı tablet başında beklemeyin.",
          "Kural ve eşik tabanlı raporlarla en çok satan ürünü, en yoğun saati ve azalan stoğu görün.",
          "Çok şubeliyseniz şube başına satışı ve ürün maliyetini yan yana karşılaştırın.",
        ],
      },
    ],
    why: [
      "Kafe temposuna göre kurgulandı: QR menü, dokunmatik POS ve mutfak ekranı tek sistemde, yoğun saatte dağılmadan çalışır.",
      "Şube başına tek mutfak ekranı; siparişler karışmadan, tek yerden ve net görünür.",
      "Arayüz 5 dilde; çok dilli ekibiniz ve yabancı misafirleriniz için tanıdık bir kullanım.",
      "Bulut tabanlı: kasadan, telefon ya da tabletin tarayıcısından aynı canlı veriye ulaşın, ayrıca program kurmayın.",
      "PayTR ile online tahsilat, nakit ve kart ödeme kaydı, gün sonu raporu tek panelde.",
      "Teslimat platformları entegre: Yemeksepeti, Getir, Trendyol ve Migros siparişleri tek ekranda toplanır.",
    ],
    faq: [
      {
        q: "QR menü nasıl çalışıyor, menü içeriği otomatik çevriliyor mu?",
        a: "Her masaya bir QR kod koyarsınız; müşteri telefonuyla menüyü açar, ürünleri görür ve siparişini verir. Sipariş doğrudan şubenizin mutfak ekranına düşer. Uygulama arayüzü 5 dili destekler; ancak ürün adı ve açıklaması gibi menü içeriğini istediğiniz dilde kendiniz girersiniz, içerik otomatik çevrilmez.",
      },
      {
        q: "Kafede kart ile ödeme alabiliyor muyum?",
        a: "Online ödemeleri PayTR altyapısıyla güvenle tahsil edersiniz. Kafede nakit ya da kartla ödeyen müşterinin ödemesini ise kasada tek dokunuşla adisyona işlersiniz. Sistemin kendi kartlı ödeme terminaliyle tahsilat özelliği şu an sunulmuyor; kart, ödeme yöntemi olarak kaydedilir.",
      },
      {
        q: "Sadakat ve puan sistemi nasıl işliyor?",
        a: "Müşteriniz telefon numarasıyla tanınır ve her harcamasında puan biriktirir. Belirlediğiniz kademelere göre sadık müşterilerinize avantaj tanımlar, biriken puanı indirim veya ödüle çevirirsiniz. Böylece sık gelen müşterinizi hatırlar ve geri dönüşünü artırırsınız.",
      },
      {
        q: "Teslimat platformlarıyla çalışıyor mu, kendi kuryemi takip edebilir miyim?",
        a: "Yemeksepeti, Getir, Trendyol ve Migros siparişleri tek panele düşer; her platform için ayrı ekran başında beklemezsiniz. Teslimatı platformun kendi kurye ağı üstlenir. Kendi kuryenizi atayıp canlı GPS ile konum takibi yapma özelliği ise bulunmuyor.",
      },
      {
        q: "Birden fazla şubem var, hepsini tek yerden yönetebilir miyim?",
        a: "Evet. Tüm şubelerinizi tek panelden yönetir, her şubenin satışını, ürün maliyetini ve stoğunu ayrı ayrı görüp yan yana karşılaştırırsınız. Her şubenin kendi mutfak ekranı ve kasası bağımsız çalışır.",
      },
    ],
    ctaTitle: "Kafenizi tek panelde yönetmeye bugün başlayın",
    hero: {
      eyebrow: "Kafeler için bulut yönetim sistemi",
      title: "Yoğun saatte sıra karışmasın, masa boş kalmasın",
      subtitle:
        "Masadaki QR menüden gelen sipariş doğrudan mutfağa düşsün, kasada kuyruk birikmesin, sabah kahvesine gelen müşteriniz puanıyla geri gelsin. HummyTummy kafenizin siparişini, ödemesini, stoğunu ve sadakatini tek panelde toplar.",
    },
    intro:
      "Bir kafede gün, sabahın ilk kahvesiyle başlar; öğle molasında ve akşamüstü tatlı saatinde zirveye çıkar. Bu yoğunlukta el yazısı adisyonlar kaybolur, kasada kuyruk uzar, hangi masanın siparişinin nerede olduğu karışır. HummyTummy; masadaki QR menüden gelen siparişi doğrudan şubenizin mutfak ekranına düşürür, dokunmatik POS'ta ödemeyi hızlandırır, sık gelen müşterinizi puan sistemiyle geri getirir. Stok ve maliyet takibinden teslimat platformlarına, gün sonu raporundan çok şubeli yönetime kadar kafenizin bütün işleyişini tek bulut panelde toplar; siz de fincanın arkasındaki işi değil, müşterinizi düşünürsünüz.",
  },
  bar: {
    blocks: [
      {
        title: "Yoğun barda saniyeler kazandıran POS",
        body: "Bar önü üç sıra olduğunda, bir masa on kişiye çıktığında ve herkes kendi içkisinin hesabını istediğinde işler karışmasın. HummyTummy ile masaya ya da bar önüne saniyede adisyon açarsınız, sipariş anında bar ekranına düşer, hesap kapanırken kişi kişi ya da içki içki bölünür. İsteyen misafir masadaki QR ile kendi hesabını telefonundan görüp online öder; böylece bar önündeki ödeme kuyruğu ortadan kalkar.",
        bullets: [
          "Masaya ya da bar önüne saniyede adisyon aç; içkiyi hazırlarken sipariş anında bar ekranına düşsün",
          "Tek hesabı kişi kişi ya da içki içki böl; herkes yalnızca kendi tükettiğini ödesin",
          "Masadaki QR ile misafir kendi hesabını telefonundan görüp online (PayTR) kapatsın",
          "Aynı masaya birden çok adisyon aç; grup dağılıp toplansa da hesap karışmasın",
        ],
      },
      {
        title: "Her şişenin hesabı tutsun: maliyet ve stok kontrolü",
        body: "Bar işinde asıl kayıp görünmez olandır: fazla dolan kadeh, kayıp şişe, maliyeti bilinmeyen kokteyl. HummyTummy her içki ve kokteyl için reçete tanımlamanıza izin verir; satış oldukça bardaki stok otomatik düşer, kritik seviyeye inen içki için eşik uyarısı alırsınız. Ay sonunda 'içki nereye gitti' sorusunu, sayım ile sistem farkını raporlayarak somut rakamlarla yanıtlarsınız.",
        bullets: [
          "Her kokteyl ve kadeh için reçete tanımla; satış oldukça bardaki içki stoğu otomatik düşsün",
          "Şişe bazında kalan stoğu anlık gör; kritik seviyeye inen içki için eşik uyarısı al",
          "Maliyet ile satış farkını incele, kâr marjı düşük içkileri menüde ayıkla",
          "Fiziki sayım ile sistemdeki stok arasındaki farkı raporla; fire ve kaçağın izini sür",
        ],
      },
      {
        title: "Masa düzeni, vardiya ve personel tek panelde",
        body: "Bar önü, masalar ve locaları kat planında birebir çizer, hangi masanın dolu hangisinin boş olduğunu tek bakışta görürsünüz. Vardiya açıp kapatır, her barmen ve garsonun cirosunu vardiya sonunda raporlarsınız. İskonto, iptal ve masa taşıma gibi hassas işlemleri rol bazlı yetkiyle sınırlar; kimin ne zaman ne yaptığını kayıt altına alırsınız.",
        bullets: [
          "Bar önü, masalar ve loca düzenini kat planında birebir çiz; doluluk durumunu anlık gör",
          "Vardiya aç-kapat; her barmen ve garsonun ciro ile sipariş performansını vardiya sonu raporla",
          "Rol bazlı yetki ver; iskonto, iptal ve masa taşımayı kimin yapabileceğini sınırla",
          "İptal, ikram ve iade hareketlerini kim yaptı, ne zaman yaptı olarak kayıt altına al",
        ],
      },
    ],
    hero: {
      eyebrow: "Bar & pub yönetim sistemi",
      title:
        "Bar temposuna yetişen POS: hesap saniyede açılır, bölünür, kapanır",
      subtitle:
        "HummyTummy; yoğun gece servisinde hızlı adisyon, masada hesap bölme, içki maliyeti ve şişe bazlı stok kontrolünü tek ekranda toplar. Barmen siparişe, siz işletmeye odaklanır.",
    },
    intro:
      "Barda tempo hiç düşmez: bar önü üç sıra olur, bir masa on kişiye çıkar, herkes kendi içkisinin hesabını ister. HummyTummy tam bu kaosta devreye girer. Barmen içkiyi hazırlarken sipariş saniyede adisyona düşer, masa dolduğunda hesabı kişi kişi ya da içki içki bölersiniz, vardiya biterken hangi barmenin ne kadar ciro yaptığını tek dokunuşla görürsünüz. Şişe bazında stok ve reçeteye dayalı maliyet takibiyle de 'bu ay içki nereye gitti' sorusu ortadan kalkar. Tablet, telefon ya da bilgisayarın tarayıcısından çalışır; ek donanım kurmadan bu gece kullanmaya başlarsınız.",
    why: [
      "Gece servisinin hızına göre tasarlandı: az dokunuşla adisyon, tek ekranda anında hesap bölme",
      "Şube başına tek bar/mutfak ekranı; siparişler karışmadan tek akışta sıraya girer",
      "İçki maliyeti ve şişe bazlı stok, reçeteyle otomatik takip edilir; fire ve kaçak rapora dökülür",
      "Masadaki QR ile misafir kendi hesabını görüp online (PayTR) öder; bar önü kuyruğu azalır",
      "Çok şubeli bar ve zincirler için merkezi yönetim; her şubenin cirosu tek panelde toplanır",
      "Arayüz 5 dilde çalışır; yabancı personelin yoğun olduğu barlarda ekip aynı sistemi rahat kullanır",
    ],
    faq: [
      {
        q: "Kalabalık bir masanın hesabını nasıl bölerim?",
        a: "Tek adisyonu kişi kişi ya da içki içki bölebilirsiniz; herkes yalnızca kendi tükettiğini öder. İsterseniz misafir masadaki QR ile kendi hesabını telefonundan görüp online (PayTR) kapatır, böylece bar önünde ödeme kuyruğu oluşmaz.",
      },
      {
        q: "İçki stoğunu şişe şişe takip edebilir miyim?",
        a: "Evet. Her kokteyl ve kadeh için reçete tanımlarsınız; satış oldukça bardaki içki stoğu otomatik düşer. Şişe bazında kalan miktarı anlık görür, kritik seviyeye inen içki için eşik uyarısı alırsınız. Bu takip kural ve eşiklere dayalıdır.",
      },
      {
        q: "Barmen ve garson performansını görebilir miyim?",
        a: "Evet. Vardiya açıp kapatır, her barmen ve garsonun cirosunu, sipariş sayısını ve açtığı adisyonları vardiya sonunda raporlarsınız. İskonto, iptal ve masa taşıma gibi işlemleri rol bazlı yetkiyle sınırlayabilirsiniz.",
      },
      {
        q: "Fire ve kayıp içkinin izini sürebilir miyim?",
        a: "Evet. Fiziki sayım ile sistemdeki stok arasındaki farkı raporlar, hangi içkide açık olduğunu görürsünüz. İptal, ikram ve iade hareketleri kim ne zaman yaptı olarak kayıt altına alınır; böylece kaçağın kaynağını somut rakamlarla takip edersiniz.",
      },
      {
        q: "Birden fazla barım var, hepsini tek yerden yönetebilir miyim?",
        a: "Evet. Çok şubeli bar ve zincirleri merkezi olarak yönetir, her şubenin cirosunu, stoğunu ve personelini tek panelde toplarsınız. Sistem tarayıcı üzerinden çalıştığı için her şubede ayrı kurulumla uğraşmazsınız.",
      },
    ],
    ctaTitle: "Barınızı bu gece HummyTummy ile yönetmeye başlayın",
  },
  pastane: {
    blocks: [
      {
        title: "Her reçete, her gram maliyetiyle kayıt altında",
        body: "Pastane ve fırın işinde kâr, çoğu zaman gramların içinde saklıdır. Bir pastanın gerçek maliyetini un, şeker, tereyağı ve yumurta fiyatları belirler; bu fiyatlar da sürekli oynar. HummyTummy'de her ürünün reçetesini tanımlarsınız, sistem porsiyon başına maliyeti sizin yerinize hesaplar. Hammadde fiyatı değiştiğinde maliyetin ve kâr marjının nasıl kaydığını anında görür, satış fiyatınızı tahminle değil rakamla belirlersiniz.",
        bullets: [
          "Her ürünün reçetesini un, şeker, tereyağı, yumurta gibi hammaddelerle tanımlayın; porsiyon maliyeti kendiliğinden çıksın",
          "Hammadde fiyatı arttığında ürün maliyetinizin ve kâr marjınızın nasıl değiştiğini anında görün",
          "Zararına ya da çok düşük marjla sattığınız ürünleri fark edin, fiyatınızı bilinçli belirleyin",
          "Onlarca çeşit üreten bir mutfakta bile her kalemin maliyetini tek tek elle hesaplamaktan kurtulun",
        ],
      },
      {
        title: "Un bitmeden, tereyağı tükenmeden haberiniz olsun",
        body: "Bir fırında en pahalı an, hammaddenin sabahın köründe bitip üretimin durduğu andır. HummyTummy sattığınız her üründe reçetedeki hammaddeyi depodan otomatik düşer, böylece stoğunuz her an gerçeği gösterir. Kritik seviyeye inen kalemler için uyarı alır, tedarikçi alımlarınızı sisteme işler ve gelen malı stoğa eklersiniz. Dönem sonunda sayım yapıp kayıt ile fiziki stok arasındaki farkı görür, israfın nereden kaynaklandığını anlarsınız.",
        bullets: [
          "Sattığınız her üründe reçetedeki hammadde depodan otomatik düşsün, stoğunuz her an güncel kalsın",
          "Kritik seviyeye inen un, tereyağı ya da çikolata için uyarı alın, tezgah boş kalmadan sipariş verin",
          "Tedarikçi alımlarınızı sisteme işleyin, gelen hammaddeyi stoğa ekleyin",
          "Dönemsel sayım yapın, kayıt ile fiziki stok arasındaki farkı ve fireyi net görün",
        ],
      },
      {
        title: "Tezgahta hızlı satış, vitrinde dijital menü",
        body: "Sabah yoğunluğunda kuyruk büyürken satışın hızlı olması gerekir. HummyTummy'nin POS ekranıyla poğaça, ekmek, pasta dilimi gibi satışları saniyeler içinde tamamlarsınız. Vitrininizdeki tüm çeşidi fotoğrafı, açıklaması ve güncel fiyatıyla QR menüde dijital olarak sergiler; müşterilerinizin QR menüden sipariş verip PayTR ile online, güvenle ödemesini sağlarsınız. Tek şubede de, birden çok fırın ve pastanede de satışın tamamı aynı panelde toplanır.",
        bullets: [
          "Poğaça, ekmek, pasta dilimi gibi hızlı satışları tezgahta saniyeler içinde tamamlayın",
          "Vitrininizdeki tüm ürünleri fotoğraf, açıklama ve güncel fiyatıyla QR menüde dijital olarak sergileyin",
          "Müşterileriniz QR menüden sipariş verip PayTR ile online ve güvenli şekilde ödesin",
          "Tek şubede de, birden çok fırın ve pastanede de tüm satışı aynı panelden takip edin",
        ],
      },
    ],
    hero: {
      eyebrow: "Pastane & Fırın Yönetimi",
      title: "Reçeteden vitrine: pastane ve fırınınız tek programda",
      subtitle:
        "Reçete ve maliyetten stok ve satınalmaya, QR menüden tezgah satışına kadar; pastane ve fırınınızın hem üretimini hem satışını tek sistemde buluşturun.",
    },
    intro:
      "Pastane ve fırın işletmeciliği aynı anda iki işi birden yürütmektir: arkada üretim, önde satış. Bir yanda un, şeker, tereyağı ve yumurtayla çalışan bir mutfak; öte yanda vitrindeki onlarca çeşidi hızla satan bir tezgah. HummyTummy bu iki tarafı tek sistemde birleştirir. Her ürünün reçetesini ve maliyetini tanımlar, sattıkça hammadde stoğunuzu otomatik düşer, tezgahta saniyeler içinde satış yapar ve vitrininizi QR menüyle internete taşırsınız. Böylece hangi ürünün gerçekten kâr ettiğini, hangi hammaddenin ne zaman biteceğini ve gün sonunda kasada ne olduğunu tahmin etmeyi bırakır, görmeye başlarsınız.",
    why: [
      "Üretim ve satışı tek sistemde birleştirir: mutfaktaki reçeteden tezgahtaki fişe kadar kopuk süreç kalmaz",
      "Reçete bazlı maliyet sayesinde her pastanın, her böreğin gerçek maliyetini ve kârını bilirsiniz",
      "Otomatik stok düşümüyle her satış sonrası hammadde deponuz kendiliğinden güncellenir",
      "QR menü ve online sipariş ile vitrininizi internete taşır, tezgaha gelmeden de sipariş alırsınız",
      "Birden çok şubeli fırın ve pastane zincirini tek panelden, şube şube yönetirsiniz",
      "Arayüz Türkçe dahil 5 dilde çalışır; farklı ekipler kendi rahat ettiği dilde kullanır",
    ],
    faq: [
      {
        q: "Ürünlerimin maliyetini ve kârını nasıl takip ederim?",
        a: "Her ürün için hammaddeleri reçeteye girersiniz; HummyTummy porsiyon başına maliyeti hesaplar. Un, tereyağı gibi fiyatlar değiştiğinde maliyetiniz ve kâr marjınız güncellenir, böylece hangi ürünün gerçekten kazandırdığını rakamla görürsünüz.",
      },
      {
        q: "Satış yaptıkça hammadde stoğum otomatik güncelleniyor mu?",
        a: "Evet. Bir ürün satıldığında reçetesindeki hammaddeler depodan otomatik düşer. Kritik stok seviyesine inen kalemler için uyarı alır, tükenmeden sipariş verirsiniz.",
      },
      {
        q: "Müşterilerim online sipariş verip ödeyebilir mi?",
        a: "Evet. Müşterileriniz QR menü üzerinden ürünleri görüp sipariş verebilir ve PayTR ile online ödeme yapabilir. Ödeme onaylandığında sipariş işletmenize düşer.",
      },
      {
        q: "e-Fatura ve muhasebe tarafında ne sağlıyorsunuz?",
        a: "Tüm satışlarınız kalem kalem kayıt altına alınır ve raporlanır; bu verileri muhasebenizle rahatça paylaşırsınız. e-Fatura/e-Arşiv için Paraşüt, Logo gibi sağlayıcılarla doğrudan entegrasyon yol haritamızda yer alıyor; hazır olduğunda faturaları sistem üzerinden kesebileceksiniz.",
      },
      {
        q: "Birden fazla şubem var, hepsini tek yerden yönetebilir miyim?",
        a: "Evet. Tüm şubelerinizi tek panelden yönetir; her şubenin satışını, stoğunu ve reçetelerini ayrı ayrı takip edersiniz. Şubeler arası karşılaştırmalı raporlarla hangi şubenin nasıl gittiğini görürsünüz.",
      },
    ],
    ctaTitle:
      "Pastanenizi ve fırınınızı bugün HummyTummy ile tek sistemde toplayın",
  },
  "fast-food": {
    blocks: [
      {
        title:
          "Kuyruğu eritin: QR menü, self-servis ödeme ve tek dokunuşluk POS",
        body: "Fast food'da kâr, saniyelerde saklıdır. Öğle patlamasında kasada biriken kuyruk, hem masayı hem ciroyu tıkar. HummyTummy'de müşteri masadaki QR koddan menüyü kendi telefonunda açar, seçer ve self-servis ekranda PayTR ile online öder; sipariş kasada kimseyi beklemeden doğrudan mutfağa düşer. Kasada tercih eden müşteri için hızlı POS ekranı en çok satan menüleri, varyantları ve ekstraları tek dokunuşta önüne getirir — personel ürün ararken zaman kaybetmez.",
        bullets: [
          "QR menü: müşteri masada kendi telefonundan seçer, sipariş anında mutfağa iner",
          "Self-servis ödeme: kasada kuyruk beklemeden PayTR üzerinden online tahsilat",
          "Hızlı POS: en çok satan ürünler, menüler ve varyantlar tek dokunuş uzağınızda",
          "Nakit, kart ve online ödeme tek ekranda kaydedilir; gün sonu tutarı net",
        ],
      },
      {
        title: "Mutfak ekranı (KDS) ile hiçbir sipariş gözden kaçmasın",
        body: "Fast food mutfağında en pahalı hata, unutulan ya da yanlış anlaşılan sipariştir. HummyTummy'nin mutfak ekranı, şubeye masadan, paketten ve teslimat platformlarından gelen tüm siparişleri geliş sırasına göre tek akışta toplar. Kağıt fiş, bağırışma ve 'bu sipariş kimindi' karmaşası biter. Personel hazırlanıyor ve hazır durumlarını tek dokunuşla günceller; hazır olan sipariş anında kasaya ve QR menüye yansır.",
        bullets: [
          "Şube başına tek mutfak ekranı: tüm siparişler geliş sırasına göre tek akışta",
          "Masa, paket ve teslimat siparişleri aynı ekranda birleşir",
          "Bekleyen siparişler süre ve renk uyarısıyla öne çıkar, unutulmaz",
          "Hazır işaretlenen sipariş kasaya ve müşterinin QR ekranına anında düşer",
        ],
      },
      {
        title: "Yemeksepeti, Getir, Trendyol ve Migros siparişleri tek panelde",
        body: "Ayrı ayrı tabletlerde çalan dört farklı platform, yoğun saatte kabus olur. HummyTummy, Yemeksepeti, Getir, Trendyol Yemek ve Migros Yemek entegrasyonuyla bu kanallardan gelen siparişleri tek panelde toplar; her sipariş otomatik olarak mutfak ekranına ve satış raporlarına düşer. Böylece masa, paket ve platform siparişleri aynı sistemde, aynı personelle yürür. Teslimatı platformların kendi kurye ağı taşır — siz sipariş ve mutfak akışına odaklanırsınız.",
        bullets: [
          "Dört teslimat platformunun siparişleri tek panelde, tek akışta toplanır",
          "Gelen her sipariş otomatik mutfak ekranına ve satış raporlarına yansır",
          "Masa, paket ve platform siparişleri aynı sistemde birlikte yönetilir",
          "Şube bazında hangi kanal ne kadar satıyor, kural tabanlı raporlarla net görün",
        ],
      },
    ],
    ctaTitle:
      "Fast food'unuzu hıza geçirin — HummyTummy'yi bugün ücretsiz deneyin",
    faq: [
      {
        q: "Kendi kuryemi atayıp canlı GPS ile takip edebilir miyim?",
        a: "Hayır. HummyTummy kurye atama veya canlı GPS takibi sunmaz. Bunun yerine Yemeksepeti, Getir, Trendyol Yemek ve Migros Yemek entegrasyonuyla bu platformların siparişlerini tek panelde toplarız; teslimatı platformların kendi kurye ağı yürütür, siz sadece sipariş ve mutfak akışını yönetirsiniz.",
      },
      {
        q: "Mutfak ekranı istasyon bazlı yönlendirme yapıyor mu (ızgara, fritöz ayrı)?",
        a: "Hayır. Her şube için tek mutfak ekranı çalışır ve tüm siparişler geliş sırasına göre tek akışta görünür. İstasyon bazlı ayrı ekran yönlendirmesi yoktur; amaç, yoğun saatte hiçbir siparişin sırasından kopmadan takip edilmesidir.",
      },
      {
        q: "Kasada kart terminaliyle tahsilat alıyor musunuz?",
        a: "Uygulama içinden fiziksel kart terminaliyle tahsilat yoktur. Online ödemeler (QR menü ve self-servis) PayTR üzerinden güvenli şekilde alınır; nakit ve kart ödemeleri ise sistemde ödeme kaydı olarak tutulur, gün sonu raporunuza işlenir.",
      },
      {
        q: "Yemek kartı (Multinet, Sodexo) ile online ödeme var mı?",
        a: "Hayır, yemek kartlarıyla online tahsilat sunmuyoruz. Online ödemeler PayTR ile işlenir; yemek kartı ödemesini kasada ödeme yöntemi olarak kaydedebilirsiniz.",
      },
      {
        q: "Kullanmak için mobil uygulama indirmek gerekiyor mu?",
        a: "Hayır. Sistem tarayıcı tabanlıdır; müşteri QR menüyü telefonunda hiçbir uygulama kurmadan açar. Personel paneli ve POS da tarayıcıdan çalışır, arayüz 5 dili destekler.",
      },
    ],
    hero: {
      eyebrow: "Fast Food & Hızlı Servis",
      title:
        "Fast food'da kazandıran tek şey hız — HummyTummy onu sisteme bağlar",
      subtitle:
        "QR menü, self-servis ödeme, tek dokunuşluk POS ve mutfak ekranı; masadan, paketten ve Yemeksepeti/Getir/Trendyol/Migros'tan gelen tüm siparişler tek akışta buluşur.",
    },
    intro:
      "Fast food işletmesinde her şey öğle ve akşam patlamasında belli olur: kasada uzayan kuyruk, mutfakta biriken fişler, aynı anda dört farklı teslimat platformundan çalan siparişler ve 'bu neydi, kimindi' karmaşası. HummyTummy tam bu yoğunluk için tasarlandı. Müşteri masadaki QR koddan sipariş verir, self-servis ekranda PayTR ile online öder; kasadaki personel hızlı POS ile en çok satan ürünleri tek dokunuşta seçer. Masadan, paketten ve teslimat platformlarından gelen her sipariş şubenin tek mutfak ekranında geliş sırasına göre toplanır, hazırlanıyor ve hazır durumlarıyla takip edilir. Tek hesaptan tüm şubelerinizin cirosunu, en çok satan ürünlerini ve saatlik yoğunluğunu kural tabanlı raporlarla görürsünüz — kağıt fiş, dağınık tablet ve yanlış anlaşılan sipariş devri kapanır.",
    why: [
      "Yoğun saatte hız: QR menü, self-servis ödeme ve hızlı POS birlikte kuyruğu eritir",
      "Sipariş doğruluğu: seçim müşteriden dijital olarak mutfağa düşer, yanlış anlaşılan sipariş biter",
      "Tek panelde çok kanal: masa, paket ve dört teslimat platformu aynı akışta birleşir",
      "Çok şube tek merkez: her şubenin cirosu, ürünleri ve mutfak akışı tek hesaptan yönetilir",
      "Online tahsilat: self-servis ve QR ödemede PayTR ile güvenli, kuyruksuz ödeme",
      "Kural tabanlı raporlar: en çok satan ürün, saatlik yoğunluk ve şube karşılaştırması net rakamlarla",
    ],
  },
  pizza: {
    blocks: [
      {
        title: "Salon, gel-al ve paket siparişleri tek panelde toplanır",
        body: "Cuma akşamı salon dolu, telefon susmuyor, Yemeksepeti ve Getir'den siparişler arka arkaya düşüyor. HummyTummy bu üç kanalı tek adisyon akışında birleştirir; personeliniz masa ile paket arasında koşarken siparişleri karıştırmaz. Her pizzayı boyutu, hamuru ve malzeme seçenekleriyle tanımlar, ekstra malzeme farklarını fiyatıyla adisyona işlersiniz.",
        bullets: [
          "Masadaki açık hesap, gel-al ve paket siparişleri tek sipariş ekranında",
          "Yemeksepeti, Getir, Trendyol ve Migros siparişleri otomatik panele düşer; ayrı platform tabletleri arasında koşmak yok",
          "Boyut (orta/büyük/aile), hamur ve malzeme seçenekleriyle her pizzayı tek dokunuşla oluştur",
          "Yarım-yarım pizza ve ekstra malzeme farklarını fiyatıyla adisyona ekle",
        ],
      },
      {
        title:
          "Fırın önündeki mutfak ekranıyla sipariş sırası gözünüzün önünde",
        body: "Onaylanan her sipariş, kanaldan bağımsız olarak fırının önündeki mutfak ekranına (KDS) sırayla düşer. Hangi pizza ne zaman girdi, ne kadar bekliyor; renkli süre takibiyle gecikmeyi büyümeden görürsünüz. Salon, gel-al ve paket siparişler aynı kuyrukta ilerler, hazır olanı tek dokunuşla kapatırsınız.",
        bullets: [
          "Her şube için tek mutfak ekranı; onaylanan sipariş anında fırının önüne düşer",
          "Sipariş bekleme sürelerini renkle takip et, geciken siparişi zamanında yakala",
          "Salon, gel-al ve platform siparişleri aynı kuyrukta sıraya girer",
          "Hazırlanan siparişi tek dokunuşla kapat, servise veya paket teslimine geç",
        ],
      },
      {
        title: "Malzeme stoğu, QR menü ve gün sonu raporları",
        body: "Mozzarella, hamur ve sos gibi kritik malzemelerde stok takibi yapar, seviye düşünce uyarı alırsınız; akşamın ortasında malzemesiz kalmazsınız. Masadaki müşteri QR menüyü okutup güncel menüyü ve fiyatları görür. Gün sonunda ciroyu, en çok satan pizzaları ve salon/paket/gel-al kanal kırılımını raporlarsınız.",
        bullets: [
          "Mozzarella, hamur ve sos stoğunu takip et; kritik seviyede uyarı al",
          "QR menü ile müşteri karekodu okutup güncel menüyü ve fiyatları görür",
          "Gün sonu ciro, en çok satan pizzalar ve kanal (salon/paket/gel-al) kırılımı",
          "Online tahsilat PayTR ile; kasada veya kapıda alınan kart/nakit ödemeleri adisyona kayıt olarak işle",
        ],
      },
    ],
    why: [
      "Akşam ve hafta sonu yoğunluğunda salon, telefon ve platform siparişlerini karıştırmadan tek panelden yönetirsiniz",
      "Fırın önündeki mutfak ekranıyla sipariş sırası ve bekleme süresi her an gözünüzün önünde olur",
      "Yemeksepeti, Getir, Trendyol ve Migros entegrasyonuyla platform siparişleri otomatik panele ve mutfak ekranına düşer",
      "Boyut, hamur ve malzeme varyasyonlarıyla pizza menünüzü ve kampanyalarınızı esnek kurarsınız",
      "Malzeme stok takibiyle mozzarella veya hamur bitmeden haberiniz olur",
      "Çok şubeli pizzacıda her şubenin cirosunu ve performansını tek yerden görürsünüz",
    ],
    faq: [
      {
        q: "Yemeksepeti ve Getir siparişleri panele otomatik düşer mi?",
        a: "Evet. Yemeksepeti, Getir, Trendyol ve Migros hesaplarınızı bağladığınızda gelen siparişler otomatik olarak sipariş panelinize ve mutfak ekranınıza düşer; personeliniz ayrı platform tabletleri arasında koşmak zorunda kalmaz.",
      },
      {
        q: "Kendi motorlu kuryemi atayıp canlı olarak takip edebilir miyim?",
        a: "Hayır. HummyTummy kendi kurye atama ve GPS ile canlı konum takibi sunmaz. Teslimat tarafını Yemeksepeti ve Getir gibi platform entegrasyonları üzerinden yönetirsiniz; sipariş ve teslim durumunu adisyon üzerinden kayıt altına alabilirsiniz.",
      },
      {
        q: "Yarım-yarım pizza ve ekstra malzeme farklarını adisyona işleyebilir miyim?",
        a: "Evet. Pizzalarınızı boyut, hamur ve malzeme seçenekleriyle tanımlar, yarım-yarım seçimlerini ve ekstra malzeme farklarını fiyatıyla adisyona ekleyebilirsiniz.",
      },
      {
        q: "Mutfak ekranı istasyon istasyon sipariş yönlendiriyor mu?",
        a: "Her şube için tek bir mutfak ekranı sunuyoruz. Onaylanan siparişler kanaldan bağımsız olarak bu ekrana sırayla düşer; ayrı istasyonlara (soğuk hazırlık/fırın) otomatik dağıtım bulunmuyor.",
      },
      {
        q: "Müşteri QR menüden ödeme yapabilir mi, kart terminaliyle tahsilat var mı?",
        a: "Müşteri QR menüyü okutup güncel menüyü görür ve sipariş verir. Online tahsilat PayTR altyapısıyla yapılır. Kart ödemesini fiziksel terminalle bu panelden tahsil etmeyiz; kasada veya kapıda alınan kart ve nakit ödemeleri adisyona kayıt olarak işlersiniz.",
      },
    ],
    ctaTitle:
      "Pizzacınızın salonunu, paketini ve mutfağını tek panelden yönetmeye bugün başlayın",
    hero: {
      eyebrow: "Pizza & Fırın İşletmeleri İçin",
      title: "Pizzacınızın salonu, paketi ve gel-al'ı tek panelde buluşuyor",
      subtitle:
        "Akşam yoğunluğunda masa siparişleri, telefon paketleri ve Yemeksepeti/Getir siparişleri birbirine karışmasın. HummyTummy ile siparişten fırın önündeki mutfak ekranına, malzeme stoğundan gün sonu raporuna kadar tüm pizzacı operasyonunuzu tek ekrandan yönetin.",
    },
    intro:
      "Cuma akşamı salon dolu, telefon susmuyor, Yemeksepeti ve Getir'den siparişler arka arkaya düşüyor; pizzacı işletmesinin en kârlı ama en kaotik saatleri tam da bunlar. HummyTummy bu kaosu tek bir panele indirir: masadaki açık hesaplar, gel-al siparişleri ve platform siparişleri aynı akışta toplanır, onaylanan her sipariş doğrudan fırının önündeki mutfak ekranına düşer. Pizzalarınızı boyut, hamur ve malzeme seçenekleriyle kurar, mozzarelladan hamura kadar stok takibini yapar, gün sonunda hangi pizzanın hangi kanalda ne kadar sattığını görürsünüz. Tek şubeden çok şubeye, tüm pizzacı operasyonunuz tek yerden yönetilir.",
  },
  burger: {
    blocks: [
      {
        title:
          "Akşam yoğunluğunu tıkanmadan çevir: POS'tan mutfağa saniyede düşen sipariş",
        body: "Cuma akşamı sıra kapıya vururken kasada kaybedilen her saniye soğuyan patates, bekleyen masa ve gerilen ekip demek. HummyTummy'nin hızlı POS ekranı en çok satan burgerlerini, menüleri ve ekstraları tek dokunuşla toplar; onaylanan sipariş anında şubenin mutfak ekranına (KDS) düşer, garson mutfağa koşmaz. 'Double köfte, ekstra cheddar, acılı sos, soğansız' gibi özelleştirmeler siparişe not olarak değil, mutfağın gördüğü net satır olarak gider; böylece yanlış hazırlanan burger ve iade tabağı azalır.",
        bullets: [
          "Adet, ekstra malzeme ve pişirme notu tek ekranda; kasadaki acemi personel bile hatasız fiş keser",
          "Onaylanan sipariş şubenin mutfak ekranına anında düşer, kağıt fiş ve 'hangi masaydı' kargaşası biter",
          "Ekstra köfte, çift peynir, patates upgrade gibi modifiye seçenekleri fiyatıyla otomatik hesaplanır",
          "Hazır olan burger KDS'te işaretlenince servis/paket tarafı da anında görür",
        ],
      },
      {
        title:
          "Yemeksepeti, Getir, Trendyol ve Migros siparişleri aynı ekranda toplansın",
        body: "Burgerin en çok satıldığı yer çoğu zaman paket ve online; ama her platformun ayrı tableti masada bip bip öter, biri gözden kaçar, biri geç onaylanır. HummyTummy; Yemeksepeti, Getir, Trendyol ve Migros siparişlerini tek panelde toplar, hepsi aynı POS ve mutfak akışına düşer. Masadaki misafir için QR menüden sipariş, salon ve paket aynı sistemde birleşir; hangi kanaldan kaç burger gittiğini tek yerden görürsün. (Kendi kurye ekibini yönetmek veya canlı harita takibi yerine, teslimatı platformların kendi kuryesiyle yürütür; sen mutfağa ve satışa odaklanırsın.)",
        bullets: [
          "Dört teslimat platformunun siparişi tek panelde, ayrı ayrı tablet dolaşmadan yönetilir",
          "Platform siparişi de salon siparişiyle aynı mutfak ekranına düşer, hazırlık akışı bölünmez",
          "QR menüyle masadaki misafir garson beklemeden sipariş verir, PayTR ile online tahsilat yapılabilir",
          "Kanal bazında satış: online mu, salon mu, paket mi çok satıyor tek raporda görünür",
        ],
      },
      {
        title:
          "Köfte, ekmek ve patatesin maliyetini gramına kadar bil, kâr eriyip gitmesin",
        body: "Burgerde marj ayrıntıda saklı: 10 gram fazla köfte, ziyan olan ekmek, biten sos yüzünden duran hat. HummyTummy'de her ürünün reçetesini tanımlarsın; bir smashburger satıldığında köfte, ekmek, cheddar ve sos stoktan otomatik düşer. Kritik seviyeye inen malzeme uyarı verir, akşam servisinin ortasında 'ekmek bitti' sürprizini yaşamazsın. Tek şube veya zincir; her şubenin satışını, maliyetini ve stoğunu tek panelden, karşılaştırmalı takip edersin.",
        bullets: [
          "Reçete bazlı stok: satılan her burgerde köfte, ekmek, peynir ve sos otomatik düşer",
          "Kritik stok uyarısı, yoğun serviste malzeme bitmeden önce haber verir",
          "Ürün ve porsiyon maliyeti net; menü fiyatının gerçekten kâr bırakıp bırakmadığını görürsün",
          "Çoklu şube: her burger şubenin cirosu, maliyeti ve en çok satanı tek panelde karşılaştırılır",
        ],
      },
    ],
    hero: {
      eyebrow: "Burger & Hamburgerci",
      title:
        "Kalabalık akşam servisinde her burger sıcak, hızlı ve tam istendiği gibi çıksın",
      subtitle:
        "HummyTummy; hızlı POS, şube mutfak ekranı (KDS), QR menü, dört teslimat platformu entegrasyonu ve reçete bazlı stok-maliyet takibini tek sistemde birleştirir. Tek dükkândan zincire, her siparişi hatasız çevirirsin.",
    },
    intro:
      "Burgercilik hız işidir: sipariş yoğunlaştığında kasa tıkanmamalı, mutfak ne pişireceğini net görmeli, paket ve online siparişler birbirine karışmamalı. HummyTummy tam bu akışı düzenler. Kasadan geçen sipariş anında şubenin mutfak ekranına düşer; 'çift köfte, ekstra cheddar, acılı, soğansız' gibi özelleştirmeler mutfağa net satır olarak gider. Yemeksepeti, Getir, Trendyol ve Migros siparişleri tek panelde toplanır, salon ve QR menü siparişleriyle aynı akışa girer. Her burgerin reçetesini tanımlarsın; satış oldukça köfte, ekmek ve sos stoktan otomatik düşer, maliyetin ve kârın gözünün önünde durur. Tek şubede de, büyüyen bir zincirde de aynı sadelikle çalışırsın.",
    why: [
      "Hızlı POS ile yoğun saatte fiş kesme hızlanır; ekstralar ve pişirme notları hatasız girilir",
      "Şube başına tek mutfak ekranı (KDS): onaylanan sipariş anında mutfağa düşer, kağıt fiş kargaşası biter",
      "Yemeksepeti, Getir, Trendyol ve Migros tek panelde; hiçbir online sipariş gözden kaçmaz",
      "Reçete bazlı stok ve maliyet: satılan her burgerde malzeme düşer, kritik stok uyarı verir",
      "QR menüyle masadaki misafir garson beklemeden sipariş verir, online tahsilat PayTR ile alınır",
      "Çoklu şube tek panelde: her şubenin cirosu, en çok satan burgeri ve maliyeti karşılaştırılabilir",
    ],
    faq: [
      {
        q: "Yemeksepeti, Getir, Trendyol ve Migros siparişleri sisteme otomatik düşüyor mu?",
        a: "Evet. Dört platformun siparişleri tek panelde toplanır ve salon siparişleriyle aynı mutfak akışına girer, böylece her platform için ayrı tablet takip etmek zorunda kalmazsın. Teslimat, platformların kendi kuryeleriyle yürür; sistem kendi kurye atama veya canlı harita takibi yapmaz.",
      },
      {
        q: "Mutfak ekranı istasyon istasyon mu çalışıyor (ızgara, paket ayrı)?",
        a: "Şube başına tek mutfak ekranı (KDS) vardır; onaylanan tüm siparişler bu ekrana düşer. İstasyon bazlı ayrı yönlendirme yoktur, ama her sipariş adet, ekstra ve notlarıyla net görünür ve hazır olduğunda işaretlenir.",
      },
      {
        q: "Çift köfte, ekstra peynir, acılı sos gibi özelleştirmeleri sistem hesaplıyor mu?",
        a: "Evet. Her ürüne modifiye seçenekleri (ekstra malzeme, upgrade, çıkarılacak malzeme) tanımlarsın; seçim yapıldığında fiyat otomatik güncellenir ve mutfağa net satır olarak iletilir.",
      },
      {
        q: "Köfte ve malzeme maliyetini takip edebilir miyim?",
        a: "Evet. Her burgerin reçetesini tanımlarsın; satış oldukça köfte, ekmek, peynir ve sos stoktan otomatik düşer. Porsiyon maliyetini görür, kritik seviyeye inen malzeme için uyarı alırsın.",
      },
      {
        q: "Müşteri masadan kartla veya online ödeyebilir mi?",
        a: "QR menüden verilen siparişlerde online tahsilat PayTR altyapısıyla alınabilir. Nakit ve kart ödemeleri kasada kaydedilir; sistem entegre kart ödeme terminaliyle tahsilat yapmaz, kart ödemesi kayıt olarak işlenir.",
      },
    ],
    ctaTitle: "Burgerciliğini hızlandırmaya hazır mısın?",
  },
  subeli: {
    blocks: [
      {
        title: "Tüm şubeleri tek hesaptan yönetin",
        body: "Zincirinizin tamamı tek bir hesapta toplanır. Menüyü merkezden kurar, her şubeye kendi fiyatını, stok durumunu ve yetkisini verirsiniz. Şube müdürü yalnızca kendi şubesini, genel müdürlük ise tüm şubeleri görür; herkes yetkisi kadarını yönetir, karışıklık olmaz.",
        bullets: [
          "Tek hesapla oturum açın, yetkinize göre bir, beş ya da elli şube arasında saniyeler içinde geçin",
          "Menüyü merkezden yönetin; her şubede ürünün fiyatını ve açık/kapalı durumunu ayrı ayrı ayarlayın",
          "Kasa, garson, mutfak ve yönetici rollerini her şube için ayrı tanımlayın, yetkiyi şubeyle sınırlayın",
          "Şube müdürü sadece kendi şubesinin verisini görür; genel müdür tüm zinciri tek ekrandan izler",
        ],
      },
      {
        title: "Şubeleri yan yana karşılaştırın",
        body: "En çok kazandıran şubeyi de, geride kalanı da rakamla görürsünüz. Tüm zincirin toplam cirosunu tek ekranda izler, merak ettiğiniz şubenin detayına tıklayıp inersiniz. Raporlar tahmine değil, gerçek satış verinize ve belirlediğiniz eşiklere dayanır.",
        bullets: [
          "Şubeleri ciro, adisyon sayısı ve ortalama sepet tutarına göre yan yana karşılaştırın",
          "Hangi ürün hangi şubede satıyor, saatlik yoğunluk nerede birikiyor net görün",
          "Tüm zincirin toplam cirosunu tek ekranda görün, tek tıkla tek şubenin detayına inin",
          "Raporlar kural ve eşik tabanlı çalışır; kararınızı hislere değil, veriye dayandırın",
        ],
      },
      {
        title: "Tüm cihazları tek ağda toplayın",
        body: "Onlarca şubenin kasası, yazıcısı ve ekranı device-mesh cihaz ağında bir arada görünür. Hangi cihazın çevrimiçi olduğunu anında anlar, her şubenin donanımını tek yerden takip edersiniz. ESC/POS termal yazıcılar fişleri otomatik basar, her şubedeki mutfak ekranı siparişi anında gösterir.",
        bullets: [
          "Tüm şubelerin kasa, yazıcı ve ekranlarını tek cihaz ağında (device-mesh) görün, arızalı olanı hemen fark edin",
          "ESC/POS termal yazıcılarla mutfak ve kasa fişlerini otomatik yazdırın",
          "Her şubede mutfak ekranı (KDS) siparişleri anında gösterir, 'hazır' durumunu tek dokunuşla geçin",
          "Yeni bir cihaz eklerken hangi şubeye ve role bağlı olduğunu belirleyin",
        ],
      },
    ],
    hero: {
      eyebrow: "Şubeli & Zincir İşletmeler için",
      title: "Tüm şubeleriniz tek hesapta, tek ekranda",
      subtitle:
        "Her şubenin menüsünü, yetkisini ve raporunu merkezden yönetin; şubeleri yan yana karşılaştırın, cihazlarınızı tek ağdan izleyin. Genel müdürlükten kasaya kadar herkes aynı sistemde çalışsın.",
    },
    intro:
      "Şubeleriniz çoğaldıkça yönetim de dağılıyor: her şube ayrı bir program, ayrı bir Excel, ayrı bir telefon trafiği. Hangi şube kâr ediyor, hangi üründe fire var, kimin yetkisi nereye kadar uzanıyor — hepsi kafanızda kalıyor. HummyTummy zincirinizin tamamını tek hesapta toplar. Menüyü merkezden yönetir, her şubeye kendi fiyatını ve yetkisini verir, tüm şubeleri aynı ekranda yan yana karşılaştırırsınız. Kasadan mutfağa, garsondan genel müdüre kadar herkes aynı sistemde çalışır; siz de nerede olursanız olun zincirin nabzını tek yerden tutarsınız.",
    why: [
      "Tek hesap, tüm şubeler: yeni şube açmak ayrı bir sistem kurmayı gerektirmez, aynı panele eklersiniz",
      "Şube bazlı yetki: her müdür kendi şubesinden sorumludur, genel müdürlük her şeyi görür",
      "Karşılaştırmalı rapor: en güçlü ve en zayıf şubeyi rakamla görür, kararı veriye dayandırırsınız",
      "Merkezi menü, esnek şube ayarı: aynı menü, şubeye göre farklı fiyat ve stok durumu",
      "Cihaz ağı: onlarca cihazı tek yerden izler, çevrimdışı kalanı anında yakalarsınız",
      "Bulut tabanlı: telefon ya da bilgisayarın tarayıcısından tüm zincire her yerden bakarsınız",
    ],
    faq: [
      {
        q: "Kaç şube ekleyebilirim?",
        a: "Zincirinizi aynı hesaba dilediğiniz kadar büyütürsünüz; şube sayısı planınıza göre artar. Yeni bir şube açtığınızda ayrı bir kurulumla uğraşmaz, mevcut hesabınıza eklersiniz.",
      },
      {
        q: "Her şube farklı menü ve fiyat kullanabilir mi?",
        a: "Evet. Menüyü merkezden yönetirsiniz, ama her şubede ürünün fiyatını, stok durumunu ve açık/kapalı olduğunu ayrı ayrı ayarlarsınız. Bir şubede satılan ürünü başka şubede kapalı tutabilirsiniz.",
      },
      {
        q: "Şube müdürü diğer şubelerin verilerini görebilir mi?",
        a: "Hayır. Yetkiler şube bazında dağıtılır; şube müdürü yalnızca kendi şubesinin adisyonlarını, raporlarını ve personelini görür. Tüm zinciri görmek genel müdürlük yetkisine bağlıdır.",
      },
      {
        q: "Ödeme türlerini nasıl alıyorum?",
        a: "Kasada nakit, kart ve diğer ödeme türlerini adisyona işaretlersiniz; kart, entegre terminal tahsilatı olarak değil, ödeme türü olarak kaydedilir. Online ödeme tarafında ise PayTR altyapısı kullanılır.",
      },
      {
        q: "Donanım olarak ne gerekiyor?",
        a: "ESC/POS uyumlu bir termal yazıcı ve tarayıcısı olan herhangi bir cihaz (kasa, tablet ya da bilgisayar) yeterlidir. Cihazlarınız device-mesh ağına bağlanır, her şubenin donanımını tek yerden görürsünüz.",
      },
    ],
    ctaTitle:
      "Zincirinizin tüm şubelerini tek panelden yönetmeye bugün başlayın",
  },
  "bulut-mutfak": {
    blocks: [
      {
        title: "Dört platformun siparişi tek akışta birleşir",
        body: "Bulut mutfağın en büyük derdi, mutfağın bir köşesinde yan yana dizili tabletler ve her platformun ayrı ekranıdır. HummyTummy, Yemeksepeti, Getir, Trendyol ve Migros'tan gelen tüm siparişleri tek bir panelde toplar. Personelin bir tabletten diğerine koşup siparişi deftere kopyalamasına gerek kalmaz; her sipariş hangi platformdan geldiği, ne zaman girildiği ve hangi aşamada olduğu net biçimde tek akışta görünür.",
        bullets: [
          "Yemeksepeti, Getir, Trendyol ve Migros siparişleri otomatik olarak aynı sipariş akışına düşer",
          "Her sipariş kaynak platformuna göre etiketlenir; hangi kanaldan geldiği tek bakışta belli",
          "Aynı mutfaktan işlettiğiniz birden fazla sanal markanın siparişleri de aynı panelde toplanır, marka bazında filtrelenir",
          "Yoğun saatte tablet başında bekleyip sipariş kaçırma riski ortadan kalkar",
        ],
      },
      {
        title: "Mutfak ekranı siparişi anlık mutfağa taşır",
        body: "Bulut mutfakta hız her şeydir: müşteri sizi görmüyor, sadece süreyi ve doğruluğu yaşıyor. Tek panele düşen her sipariş, şubenizin mutfak ekranına (KDS) anında yansır. Ekip yeni siparişi sesli ve görsel uyarıyla fark eder, hazırlık aşamalarını tek dokunuşla ilerletir ve hiçbir sipariş gözden kaçmaz. Şube başına tek, sade bir mutfak ekranı kullanılır; karmaşık istasyon kurgusuyla uğraşmadan tüm siparişleri aynı yerden yönetirsiniz.",
        bullets: [
          "Tüm platform siparişleri şubenizin mutfak ekranına gerçek zamanlı düşer",
          "Hazırlanıyor / Hazır / Teslime çıktı durumlarıyla akışı adım adım kontrol edersiniz",
          "Yeni sipariş sesli ve görsel uyarıyla bildirilir; yoğun saatte atlama olmaz",
          "Bekleyen ve geciken siparişler öne çıkar, önce hangisine bakılacağı belli olur",
        ],
      },
      {
        title: "Stok ve raporlar tek yerde, tahmine yer bırakmadan",
        body: 'Birden fazla platforma ve markaya satış yaparken "hangi ürün nerede tutuyor, malzeme ne zaman bitecek" sorusu kolayca kontrolden çıkar. HummyTummy satışla birlikte stoğu düşer, malzeme kritik eşiğin altına inince kural tabanlı uyarı verir ve platform ile marka bazında satış, ciro ve ürün raporlarını tek ekranda toplar. Raporlar sabit kurallara ve eşiklere göre çalışır; gizli bir tahmin değil, sayılara dayalı net bir tablo görürsünüz.',
        bullets: [
          "Satış gerçekleştikçe malzeme/ürün stoğu otomatik düşer, sayım yükü azalır",
          "Kritik stok eşiğinin altına inen kalemler için kural tabanlı uyarı",
          "Platform ve marka bazında satış, ciro ve çok satan ürün raporları tek panelde",
          "Hangi ürünün hangi platformda daha çok sattığını yan yana karşılaştırırsınız",
        ],
      },
    ],
    why: [
      "Sadece teslimat modeline göre kurgulandı: masa-adisyon karmaşası yerine sipariş hızı ve doğruluğu önceliğiniz olur",
      "Yemeksepeti, Getir, Trendyol ve Migros tek panelde birleşir; mutfaktaki tablet kalabalığı ve kanal karmaşası biter",
      "Aynı mutfaktan yürüttüğünüz birden fazla sanal markayı tek ekrandan yönetir, marka bazında raporlarsınız",
      "Bulut tabanlı çalışır: mutfaktaki ekran, ofisteki bilgisayar ve telefon tarayıcısı hep aynı güncel veriyi gösterir",
      "Arayüz Türkçe dahil 5 dilde; farklı vardiya ve ekiplerle çalışmak kolaylaşır",
      "Hafif kurulum: yeni pahalı donanım almadan, elinizdeki cihazlarla kısa sürede başlarsınız",
    ],
    faq: [
      {
        q: "Kendi kuryemi atayıp canlı GPS ile takip edebilir miyim?",
        a: "Hayır. HummyTummy kurye atama ve canlı GPS/rota takibi yapmaz. Teslimatı Yemeksepeti, Getir, Trendyol ve Migros kendi kurye ağlarıyla yürütür; biz bu platformlardan gelen siparişleri tek panelde toplar, mutfağınızı, stoğunuzu ve raporlarınızı yönetiriz.",
      },
      {
        q: "Hangi teslimat platformlarıyla çalışıyor?",
        a: "Yemeksepeti, Getir, Trendyol ve Migros siparişleri tek panele akar. Böylece her platform için ayrı tablet ve ayrı ekran takip etmek yerine tüm siparişleri aynı akışta görürsünüz.",
      },
      {
        q: "Aynı mutfaktan birden fazla sanal marka işletiyorum, hepsini tek yerden yönetebilir miyim?",
        a: "Evet. İşlettiğiniz tüm sanal markaların siparişleri aynı panele düşer; marka ve platform bazında filtreleyebilir, ayrı ayrı satış ve ürün raporları alabilirsiniz.",
      },
      {
        q: "Teslimat siparişlerinin ödemesini sizin üzerinizden mi tahsil ediyorum?",
        a: "Hayır. Teslimat siparişlerinin ödemesini müşteriden ilgili platform tahsil eder; bu siparişler HummyTummy'de kaydedilir ve raporlanır. Sistemdeki 'kart' seçeneği tahsilat değil, ödeme türünün kaydıdır.",
      },
      {
        q: "Satışlarımı ve stoğumu nasıl takip ederim, raporlar hazır mı?",
        a: "Platform ve marka bazında satış, ciro ve çok satan ürün raporları panelde hazır gelir. Stok, satışla birlikte düşer ve kritik eşiğin altına inen malzemeler için kural tabanlı uyarı alırsınız; raporlar sabit kurallara ve eşiklere göre çalışır.",
      },
    ],
    ctaTitle:
      "Tüm platform siparişlerinizi tek panelde toplamaya bugün başlayın",
    hero: {
      eyebrow: "Bulut Mutfak Yönetimi",
      title:
        "Yemeksepeti, Getir, Trendyol ve Migros — hepsi tek mutfak panelinde",
      subtitle:
        "Sadece teslimat üzerine çalışan bulut mutfaklar için: dört platformun siparişini tek ekranda birleştirin, mutfağı hızlandırın, stok ve raporları tek yerden yönetin.",
    },
    intro:
      "HummyTummy, masası ve salonu olmayan, işini tamamen teslimat üzerine kuran bulut mutfaklar için tasarlandı. Yemeksepeti, Getir, Trendyol ve Migros'tan gelen tüm siparişleri tek bir ekranda toplar; ayrı ayrı tabletler arasında koşmayı, siparişi elle deftere yazmayı ve yoğun saatteki platform kargaşasını ortadan kaldırır. Aynı mutfaktan birden fazla sanal marka işletiyor olsanız bile her siparişin hangi platformdan geldiğini, ne zaman girildiğini ve mutfağın hangi aşamada olduğunu tek bakışta görürsünüz. Siparişler anlık olarak mutfak ekranına düşer, satışla birlikte stok azalır ve platform ile marka bazında raporlar tek yerde birikir — böylece tüm dikkatinizi tek işe, siparişi hızlı ve doğru hazırlamaya verirsiniz.",
  },
};
