import { useState, useEffect, useCallback, useRef } from 'react'
import {
  Settings,
  X,
  Palette,
  Sparkles,
  Armchair,
  Lamp,
  TreePine,
  Maximize2,
  Link,
  Unlink,
} from 'lucide-react'
import { useVoxelStore } from '../../../store/voxelStore'
import { type TableStylePreset } from '../../../utils/procedural'
import { generateAllChairs } from '../../../utils/procedural/chairGenerator'
import { generateAllDecor, removeAutoGeneratedDecor } from '../../../utils/procedural/decorGenerator'
import type { VoxelObject } from '../../../types/voxel'
import { cn } from '@/lib/utils'

interface RTSSettingsPanelProps {
  onClose: () => void
}

const MIN_SIZE = 16
const MAX_SIZE = 64
const MIN_HEIGHT = 3
const MAX_HEIGHT = 16

const WALL_LABELS: Record<string, string> = {
  back: 'Back',
  right: 'Right',
  front: 'Front',
  left: 'Left',
}

const PRESETS = [
  { name: 'Small', width: 20, depth: 20 },
  { name: 'Medium', width: 32, depth: 32 },
  { name: 'Large', width: 48, depth: 48 },
  { name: 'Wide', width: 48, depth: 32 },
]

export function RTSSettingsPanel({ onClose }: RTSSettingsPanelProps) {
  const [selectedStyle, setSelectedStyle] = useState<TableStylePreset>('casual')
  const panelRef = useRef<HTMLDivElement>(null)

  const layout = useVoxelStore((state) => state.layout)
  const floorCells = useVoxelStore((state) => state.floorCells)
  const addObject = useVoxelStore((state) => state.addObject)
  const pushHistory = useVoxelStore((state) => state.pushHistory)
  const snapConfig = useVoxelStore((state) => state.snapConfig)
  const setSnapConfig = useVoxelStore((state) => state.setSnapConfig)
  const setLayoutDimensions = useVoxelStore((state) => state.setLayoutDimensions)
  const wallVisibility = useVoxelStore((state) => state.wallVisibility)
  const toggleWall = useVoxelStore((state) => state.toggleWall)

  const objects = layout?.objects ?? []
  const dimensions = layout?.dimensions ?? { width: 32, height: 8, depth: 32 }
  const hasTables = objects.some((obj) => obj.type === 'table')
  const hasObjects = objects.length > 0

  const [isLinked, setIsLinked] = useState(dimensions.width === dimensions.depth)

  const stylePresets: { id: TableStylePreset; label: string; desc: string }[] = [
    { id: 'casual', label: 'Casual', desc: 'Light wood, modern' },
    { id: 'formal', label: 'Formal', desc: 'Dark wood, classic' },
    { id: 'modern', label: 'Modern', desc: 'Metal, round tops' },
    { id: 'bistro', label: 'Bistro', desc: 'Dark wood, pedestal' },
  ]

  const handleClickOutside = useCallback(
    (e: MouseEvent) => {
      if (panelRef.current && !panelRef.current.contains(e.target as Node)) {
        onClose()
      }
    },
    [onClose]
  )

  const handleKeyDown = useCallback(
    (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        onClose()
      }
    },
    [onClose]
  )

  useEffect(() => {
    document.addEventListener('mousedown', handleClickOutside)
    document.addEventListener('keydown', handleKeyDown)
    return () => {
      document.removeEventListener('mousedown', handleClickOutside)
      document.removeEventListener('keydown', handleKeyDown)
    }
  }, [handleClickOutside, handleKeyDown])

  const handleGenerateChairs = useCallback(() => {
    const tables = objects.filter((o) => o.type === 'table')
    const existingChairs = objects.filter((o) => o.type === 'chair')
    const newChairs = generateAllChairs(tables, existingChairs)

    for (const chair of newChairs) {
      addObject(chair as VoxelObject)
    }
    pushHistory()
  }, [objects, addObject, pushHistory])

  const handleGenerateDecor = useCallback(() => {
    const cleanedObjects = removeAutoGeneratedDecor(objects)
    const newDecor = generateAllDecor(dimensions, cleanedObjects, {
      plants: true,
      lamps: true,
      art: true,
    }, floorCells)

    for (const decor of newDecor) {
      addObject(decor)
    }
    pushHistory()
  }, [objects, dimensions, floorCells, addObject, pushHistory])

  const handleWidthChange = useCallback(
    (value: number) => {
      const clamped = Math.max(MIN_SIZE, Math.min(MAX_SIZE, value))
      if (isLinked) {
        setLayoutDimensions(clamped, clamped)
      } else {
        setLayoutDimensions(clamped, dimensions.depth)
      }
    },
    [isLinked, dimensions.depth, setLayoutDimensions]
  )

  const handleDepthChange = useCallback(
    (value: number) => {
      const clamped = Math.max(MIN_SIZE, Math.min(MAX_SIZE, value))
      if (isLinked) {
        setLayoutDimensions(clamped, clamped)
      } else {
        setLayoutDimensions(dimensions.width, clamped)
      }
    },
    [isLinked, dimensions.width, setLayoutDimensions]
  )

  const handleHeightChange = useCallback(
    (value: number) => {
      const clamped = Math.max(MIN_HEIGHT, Math.min(MAX_HEIGHT, value))
      setLayoutDimensions(dimensions.width, dimensions.depth, clamped)
    },
    [dimensions.width, dimensions.depth, setLayoutDimensions]
  )

  return (
    <div
      ref={panelRef}
      className="absolute bottom-20 right-4 z-40 w-72 max-h-[400px] rounded-xl bg-white/95 shadow-xl backdrop-blur-md border border-slate-200 overflow-hidden"
    >
      {/* Header */}
      <div className="flex items-center justify-between border-b border-slate-200 px-4 py-2">
        <div className="flex items-center gap-2">
          <Settings className="h-4 w-4 text-primary" />
          <h3 className="text-sm font-semibold text-slate-900">Settings</h3>
        </div>
        <button
          onClick={onClose}
          className="rounded p-1 text-slate-400 transition-colors hover:bg-slate-100 hover:text-slate-600"
        >
          <X className="h-4 w-4" />
        </button>
      </div>

      {/* Content */}
      <div className="overflow-y-auto max-h-[350px] divide-y divide-slate-100">
        {/* Style Presets */}
        <div className="p-3">
          <h4 className="mb-2 flex items-center gap-1.5 text-xs font-medium uppercase text-slate-400">
            <Palette className="h-3.5 w-3.5" />
            Table Style
          </h4>
          <div className="grid grid-cols-2 gap-1.5">
            {stylePresets.map((preset) => (
              <button
                key={preset.id}
                onClick={() => setSelectedStyle(preset.id)}
                className={cn(
                  'rounded-lg px-2.5 py-2 text-left transition-all',
                  selectedStyle === preset.id
                    ? 'bg-primary/10 ring-1 ring-primary'
                    : 'bg-slate-50 hover:bg-slate-100'
                )}
              >
                <div className="text-xs font-medium text-slate-800">{preset.label}</div>
                <div className="text-[10px] text-slate-500">{preset.desc}</div>
              </button>
            ))}
          </div>
        </div>

        {/* Auto-Generate */}
        <div className="p-3">
          <h4 className="mb-2 flex items-center gap-1.5 text-xs font-medium uppercase text-slate-400">
            <Sparkles className="h-3.5 w-3.5" />
            Auto-Generate
          </h4>
          <div className="flex flex-col gap-1.5">
            <button
              onClick={handleGenerateChairs}
              disabled={!hasTables}
              className={cn(
                'flex items-center gap-2 rounded-lg px-3 py-2 text-sm transition-all',
                hasTables
                  ? 'bg-emerald-50 text-emerald-700 hover:bg-emerald-100'
                  : 'cursor-not-allowed bg-slate-50 text-slate-400'
              )}
            >
              <Armchair className="h-4 w-4" />
              <span>Generate Chairs</span>
            </button>
            <button
              onClick={handleGenerateDecor}
              disabled={!hasObjects}
              className={cn(
                'flex items-center gap-2 rounded-lg px-3 py-2 text-sm transition-all',
                hasObjects
                  ? 'bg-amber-50 text-amber-700 hover:bg-amber-100'
                  : 'cursor-not-allowed bg-slate-50 text-slate-400'
              )}
            >
              <div className="flex gap-1">
                <Lamp className="h-4 w-4" />
                <TreePine className="h-4 w-4" />
              </div>
              <span>Generate Decor</span>
            </button>
          </div>
        </div>

        {/* Snap Settings */}
        <div className="p-3">
          <h4 className="mb-2 text-xs font-medium uppercase text-slate-400">Snap Settings</h4>
          <div className="flex flex-col gap-2">
            <label className="flex items-center justify-between">
              <span className="text-sm text-slate-700">Enable Snap</span>
              <input
                type="checkbox"
                checked={snapConfig.enabled}
                onChange={(e) => setSnapConfig({ enabled: e.target.checked })}
                className="h-4 w-4 rounded border-slate-300 text-primary focus:ring-primary"
              />
            </label>
            <label className="flex items-center justify-between">
              <span className="text-sm text-slate-700">Show Guides</span>
              <input
                type="checkbox"
                checked={snapConfig.showGuides}
                onChange={(e) => setSnapConfig({ showGuides: e.target.checked })}
                className="h-4 w-4 rounded border-slate-300 text-primary focus:ring-primary"
              />
            </label>
            <div>
              <label className="mb-1 block text-sm text-slate-700">Grid Size</label>
              <input
                type="range"
                min="0.25"
                max="1"
                step="0.25"
                value={snapConfig.gridSize}
                onChange={(e) => setSnapConfig({ gridSize: parseFloat(e.target.value) })}
                className="w-full accent-primary"
              />
              <div className="text-xs text-slate-500">{snapConfig.gridSize} units</div>
            </div>
          </div>
        </div>

        {/* Dimensions */}
        <div className="p-3">
          <h4 className="mb-2 flex items-center gap-1.5 text-xs font-medium uppercase text-slate-400">
            <Maximize2 className="h-3.5 w-3.5" />
            Dimensions ({dimensions.width}x{dimensions.depth}x{dimensions.height})
          </h4>
          <div className="flex flex-col gap-2">
            <div>
              <div className="flex items-center justify-between">
                <label className="text-xs text-slate-500">Width</label>
                <span className="text-xs font-medium text-slate-700">{dimensions.width}</span>
              </div>
              <input
                type="range"
                min={MIN_SIZE}
                max={MAX_SIZE}
                value={dimensions.width}
                onChange={(e) => handleWidthChange(Number(e.target.value))}
                className="h-2 w-full cursor-pointer appearance-none rounded-lg bg-slate-200 accent-primary"
              />
            </div>

            <button
              onClick={() => {
                if (!isLinked) {
                  setLayoutDimensions(dimensions.width, dimensions.width)
                }
                setIsLinked((prev) => !prev)
              }}
              className={cn(
                'flex items-center justify-center gap-1.5 rounded py-1 text-xs transition-colors',
                isLinked
                  ? 'bg-primary/10 text-primary'
                  : 'bg-slate-100 text-slate-500 hover:text-slate-700'
              )}
            >
              {isLinked ? <Link className="h-3 w-3" /> : <Unlink className="h-3 w-3" />}
              {isLinked ? 'Square (Linked)' : 'Independent'}
            </button>

            <div>
              <div className="flex items-center justify-between">
                <label className="text-xs text-slate-500">Depth</label>
                <span className="text-xs font-medium text-slate-700">{dimensions.depth}</span>
              </div>
              <input
                type="range"
                min={MIN_SIZE}
                max={MAX_SIZE}
                value={dimensions.depth}
                onChange={(e) => handleDepthChange(Number(e.target.value))}
                disabled={isLinked}
                className={cn(
                  'h-2 w-full cursor-pointer appearance-none rounded-lg bg-slate-200 accent-primary',
                  isLinked && 'cursor-not-allowed opacity-50'
                )}
              />
            </div>

            <div>
              <div className="flex items-center justify-between">
                <label className="text-xs text-slate-500">Wall Height</label>
                <span className="text-xs font-medium text-slate-700">{dimensions.height}m</span>
              </div>
              <input
                type="range"
                min={MIN_HEIGHT}
                max={MAX_HEIGHT}
                value={dimensions.height}
                onChange={(e) => handleHeightChange(Number(e.target.value))}
                className="h-2 w-full cursor-pointer appearance-none rounded-lg bg-slate-200 accent-primary"
              />
            </div>

            {/* Wall visibility */}
            <div>
              <span className="text-xs text-slate-500">Walls</span>
              <div className="mt-1 grid grid-cols-4 gap-1">
                {(['back', 'right', 'front', 'left'] as const).map((wall) => (
                  <button
                    key={wall}
                    onClick={() => toggleWall(wall)}
                    className={cn(
                      'rounded px-2 py-1 text-xs transition-colors',
                      wallVisibility[wall]
                        ? 'bg-primary text-white'
                        : 'bg-slate-100 text-slate-500 hover:bg-slate-200'
                    )}
                  >
                    {WALL_LABELS[wall]}
                  </button>
                ))}
              </div>
            </div>

            {/* Size presets */}
            <div>
              <span className="text-xs text-slate-500">Presets</span>
              <div className="mt-1 grid grid-cols-4 gap-1">
                {PRESETS.map((preset) => {
                  const isActive = dimensions.width === preset.width && dimensions.depth === preset.depth
                  return (
                    <button
                      key={preset.name}
                      onClick={() => {
                        setLayoutDimensions(preset.width, preset.depth)
                        setIsLinked(preset.width === preset.depth)
                      }}
                      className={cn(
                        'flex flex-col items-center rounded px-1 py-1 text-xs transition-colors',
                        isActive
                          ? 'bg-primary text-white'
                          : 'bg-slate-100 text-slate-500 hover:bg-slate-200'
                      )}
                    >
                      <span className="font-medium">{preset.name}</span>
                      <span className="text-[9px] opacity-70">{preset.width}x{preset.depth}</span>
                    </button>
                  )
                })}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
