import { Injectable } from "@nestjs/common";
import { ZReport, Tenant } from "@prisma/client";
import PDFDocument from "pdfkit";
import { format } from "date-fns";
import { resolveCountryProfile } from "../../../common/country/country.service";
import { formatMoneyForDocument } from "../../../common/country/money-format";

/**
 * Pure Z-Report PDF renderer, extracted verbatim from
 * ZReportsService.generatePdf (god-file split). Takes the already-fetched
 * report + tenant and returns the document bytes — no DB access — so the
 * rendering logic is independently testable and the service keeps only the
 * fetch + delegation.
 *
 * Task 13: money used to hardcode 2 fraction digits and look up a currency
 * symbol that silently fell back to "$" for anything not in a fixed map
 * (UZS included — an Uzbek restaurant's end-of-day report printed a dollar
 * sign). Both now come from `resolveCountryProfile(tenant.countryCode)` —
 * the pure, non-DI door to the country profile (this class stays DB-free,
 * per its own doc comment above) — via the shared server-side money
 * formatter, common/country/money-format.ts. Deliberately NOT
 * `tenant.currency`: that field is a written mirror, never the truth (see
 * CountryService's class doc comment) — the profile derived from the
 * tenant's COUNTRY is canonical.
 */
@Injectable()
export class ZReportPdfService {
  render(report: ZReport, tenant: Tenant): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50 });
      const chunks: Buffer[] = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      // Header
      doc.fontSize(20).text("Z-REPORT", { align: "center" });
      doc.fontSize(12).text(tenant.name, { align: "center" });
      doc.moveDown();

      doc.fontSize(12).text(`Report Number: ${report.reportNumber}`);
      doc.text(`Date: ${format(new Date(report.reportDate), "MMMM dd, yyyy")}`);
      doc.text(
        `Generated: ${format(new Date(report.createdAt), "MMMM dd, yyyy HH:mm")}`,
      );
      doc.moveDown();

      // Country-profile-driven money — see class doc comment above.
      const profile = resolveCountryProfile(tenant.countryCode);
      const money = (amount: unknown) =>
        formatMoneyForDocument(Number(amount), profile);

      // Sales Summary
      doc.fontSize(14).text("Sales Summary", { underline: true });
      doc.fontSize(10);
      doc.text(`Total Orders: ${report.totalOrders}`);
      doc.text(`Total Sales: ${money(report.totalSales)}`);
      doc.text(`Discounts: ${money(report.totalDiscount)}`);
      doc.text(`Net Sales: ${money(report.netSales)}`);
      doc.moveDown();

      // Payment Methods
      doc.fontSize(14).text("Payment Methods", { underline: true });
      doc.fontSize(10);
      doc.text(`Cash: ${money(report.cashPayments)}`);
      doc.text(`Card: ${money(report.cardPayments)}`);
      doc.text(`Digital: ${money(report.digitalPayments)}`);
      doc.moveDown();

      // Cash Drawer
      doc.fontSize(14).text("Cash Drawer Reconciliation", { underline: true });
      doc.fontSize(10);
      doc.text(`Opening Balance: ${money(report.openingCash)}`);
      doc.text(`Cash Sales: ${money(report.cashPayments)}`);
      doc.text(`Expected Cash: ${money(report.expectedCash)}`);
      doc.text(`Actual Cash: ${money(report.countedCash)}`);
      doc.text(`Difference: ${money(report.cashDifference)}`, {
        continued: true,
      });

      const cashDiff = Number(report.cashDifference);
      if (cashDiff !== 0) {
        doc
          .fillColor(cashDiff > 0 ? "green" : "red")
          .text(` (${cashDiff > 0 ? "Over" : "Short"})`)
          .fillColor("black");
      }
      doc.moveDown();

      // Notes
      if (report.notes) {
        doc.fontSize(14).text("Notes", { underline: true });
        doc.fontSize(10).text(report.notes);
        doc.moveDown();
      }

      // Footer
      doc
        .fontSize(8)
        .text(`Generated by ${tenant.name} POS System`, { align: "center" })
        .text(`Report ID: ${report.id}`, { align: "center" });

      doc.end();
    });
  }
}
