import { Injectable } from "@nestjs/common";
import { ZReport, Tenant } from "@prisma/client";
import PDFDocument from "pdfkit";
import { format } from "date-fns";
import { CURRENCY_SYMBOLS } from "../currency-symbols";

/**
 * Pure Z-Report PDF renderer, extracted verbatim from
 * ZReportsService.generatePdf (god-file split). Takes the already-fetched
 * report + tenant and returns the document bytes — no DB access — so the
 * rendering logic is independently testable and the service keeps only the
 * fetch + delegation.
 */
@Injectable()
export class ZReportPdfService {
  render(report: ZReport, tenant: Tenant): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50 });
      const chunks: Buffer[] = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      // Header
      doc.fontSize(20).text("Z-REPORT", { align: "center" });
      doc.fontSize(12).text(tenant.name, { align: "center" });
      doc.moveDown();

      doc.fontSize(12).text(`Report Number: ${report.reportNumber}`);
      doc.text(`Date: ${format(new Date(report.reportDate), "MMMM dd, yyyy")}`);
      doc.text(
        `Generated: ${format(new Date(report.createdAt), "MMMM dd, yyyy HH:mm")}`,
      );
      doc.moveDown();

      // Get currency symbol
      const currencySymbol = CURRENCY_SYMBOLS[tenant.currency] || "$";

      // Sales Summary
      doc.fontSize(14).text("Sales Summary", { underline: true });
      doc.fontSize(10);
      doc.text(`Total Orders: ${report.totalOrders}`);
      doc.text(
        `Total Sales: ${currencySymbol}${Number(report.totalSales).toFixed(2)}`,
      );
      doc.text(
        `Discounts: ${currencySymbol}${Number(report.totalDiscount).toFixed(2)}`,
      );
      doc.text(
        `Net Sales: ${currencySymbol}${Number(report.netSales).toFixed(2)}`,
      );
      doc.moveDown();

      // Payment Methods
      doc.fontSize(14).text("Payment Methods", { underline: true });
      doc.fontSize(10);
      doc.text(
        `Cash: ${currencySymbol}${Number(report.cashPayments).toFixed(2)}`,
      );
      doc.text(
        `Card: ${currencySymbol}${Number(report.cardPayments).toFixed(2)}`,
      );
      doc.text(
        `Digital: ${currencySymbol}${Number(report.digitalPayments).toFixed(2)}`,
      );
      doc.moveDown();

      // Cash Drawer
      doc.fontSize(14).text("Cash Drawer Reconciliation", { underline: true });
      doc.fontSize(10);
      doc.text(
        `Opening Balance: ${currencySymbol}${Number(report.openingCash).toFixed(2)}`,
      );
      doc.text(
        `Cash Sales: ${currencySymbol}${Number(report.cashPayments).toFixed(2)}`,
      );
      doc.text(
        `Expected Cash: ${currencySymbol}${Number(report.expectedCash).toFixed(2)}`,
      );
      doc.text(
        `Actual Cash: ${currencySymbol}${Number(report.countedCash).toFixed(2)}`,
      );
      doc.text(
        `Difference: ${currencySymbol}${Number(report.cashDifference).toFixed(2)}`,
        {
          continued: true,
        },
      );

      const cashDiff = Number(report.cashDifference);
      if (cashDiff !== 0) {
        doc
          .fillColor(cashDiff > 0 ? "green" : "red")
          .text(` (${cashDiff > 0 ? "Over" : "Short"})`)
          .fillColor("black");
      }
      doc.moveDown();

      // Notes
      if (report.notes) {
        doc.fontSize(14).text("Notes", { underline: true });
        doc.fontSize(10).text(report.notes);
        doc.moveDown();
      }

      // Footer
      doc
        .fontSize(8)
        .text(`Generated by ${tenant.name} POS System`, { align: "center" })
        .text(`Report ID: ${report.id}`, { align: "center" });

      doc.end();
    });
  }
}
