export default {
  "index": "Overview",
  "dashboard": "Dashboard",
  "pos": "POS (Sales Screen)",
  "kitchen": "Kitchen Display (KDS)",
  "orders": "Orders",
  "tables": "Tables & Floor Plan",
  "menu": "Menu Management",
  "qr-menu": "QR Menu",
  "qr-codes": "QR Codes",
  "customers": "Customers",
  "reservations": "Reservations",
  "users": "Users & Roles",
  "personnel": "Personnel",
  "stock": "Stock & Inventory",
  "invoices": "Invoices",
  "reports": "Reports",
  "analytics": "Analytics",
  "branches": "Branches",
  "devices": "Devices",
  "bridges": "Bridges",
  "health": "System Health",
  "fiscal-recovery": "Fiscal Recovery",
  "settings": "Settings",
  "online-orders": "Online Ordering",
};
