import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Sparkles, Palette, Armchair, Lamp, TreePine } from 'lucide-react'
import { useVoxelStore } from '../../store/voxelStore'
import { TABLE_STYLE_PRESETS, type TableStylePreset } from '../../utils/procedural'
import { generateAllChairs } from '../../utils/procedural/chairGenerator'
import { generateAllDecor, removeAutoGeneratedDecor } from '../../utils/procedural/decorGenerator'
import type { VoxelObject } from '../../types/voxel'
import { cn } from '@/lib/utils'

interface ProceduralGenerationPanelProps {
  onStyleChange?: (preset: TableStylePreset) => void
}

export function ProceduralGenerationPanel({
  onStyleChange,
}: ProceduralGenerationPanelProps) {
  const { t } = useTranslation()
  const [selectedStyle, setSelectedStyle] = useState<TableStylePreset>('casual')

  const layout = useVoxelStore((state) => state.layout)
  const addObject = useVoxelStore((state) => state.addObject)
  const pushHistory = useVoxelStore((state) => state.pushHistory)
  const snapConfig = useVoxelStore((state) => state.snapConfig)
  const setSnapConfig = useVoxelStore((state) => state.setSnapConfig)

  const objects = layout?.objects ?? []
  const dimensions = layout?.dimensions ?? { width: 32, height: 8, depth: 32 }

  const hasTables = objects.some((obj) => obj.type === 'table')
  const hasObjects = objects.length > 0

  const stylePresets: { id: TableStylePreset; label: string; description: string }[] = [
    { id: 'casual', label: t('voxel.procgen.casual', 'Casual'), description: t('voxel.procgen.casualDesc', 'Light wood, modern style') },
    { id: 'formal', label: t('voxel.procgen.formal', 'Formal'), description: t('voxel.procgen.formalDesc', 'Dark wood, classic legs') },
    { id: 'modern', label: t('voxel.procgen.modern', 'Modern'), description: t('voxel.procgen.modernDesc', 'Metal, round tops') },
    { id: 'bistro', label: t('voxel.procgen.bistro', 'Bistro'), description: t('voxel.procgen.bistroDesc', 'Dark wood, pedestal') },
  ]

  const handleGenerateChairs = () => {
    const tables = objects.filter((o) => o.type === 'table')
    const existingChairs = objects.filter((o) => o.type === 'chair')
    const newChairs = generateAllChairs(tables, existingChairs)

    for (const chair of newChairs) {
      addObject(chair as VoxelObject)
    }

    pushHistory()
  }

  const handleGenerateDecor = () => {
    // Remove previously auto-generated decor
    const cleanedObjects = removeAutoGeneratedDecor(objects)

    // Generate new decor
    const newDecor = generateAllDecor(dimensions, cleanedObjects, {
      plants: true,
      lamps: true,
      art: true,
    })

    for (const decor of newDecor) {
      addObject(decor)
    }

    pushHistory()
  }

  const handleStyleChange = (preset: TableStylePreset) => {
    setSelectedStyle(preset)
    onStyleChange?.(preset)
  }

  return (
    <div className="flex flex-col gap-3">
      {/* Style Presets */}
      <div className="rounded-lg bg-gray-800 p-3">
        <h3 className="mb-2 flex items-center gap-2 text-xs font-medium uppercase text-gray-400">
          <Palette className="h-3.5 w-3.5" />
          {t('voxel.procgen.tableStyle', 'Table Style')}
        </h3>
        <div className="grid grid-cols-2 gap-1.5">
          {stylePresets.map((preset) => (
            <button
              key={preset.id}
              onClick={() => handleStyleChange(preset.id)}
              className={cn(
                'rounded-lg px-2.5 py-2 text-left transition-all',
                selectedStyle === preset.id
                  ? 'bg-blue-500/20 ring-1 ring-blue-500'
                  : 'bg-gray-700 hover:bg-gray-600'
              )}
            >
              <div className="text-xs font-medium text-white">{preset.label}</div>
              <div className="text-[10px] text-gray-400">{preset.description}</div>
            </button>
          ))}
        </div>
      </div>

      {/* Procedural Generation */}
      <div className="rounded-lg bg-gray-800 p-3">
        <h3 className="mb-2 flex items-center gap-2 text-xs font-medium uppercase text-gray-400">
          <Sparkles className="h-3.5 w-3.5" />
          {t('voxel.procgen.autoGenerate', 'Auto-Generate')}
        </h3>
        <div className="flex flex-col gap-1.5">
          <button
            onClick={handleGenerateChairs}
            disabled={!hasTables}
            className={cn(
              'flex items-center gap-2 rounded-lg px-3 py-2 text-sm transition-all',
              hasTables
                ? 'bg-emerald-600/20 text-emerald-400 hover:bg-emerald-600/30'
                : 'cursor-not-allowed bg-gray-700 text-gray-500'
            )}
          >
            <Armchair className="h-4 w-4" />
            <span>{t('voxel.procgen.generateChairs', 'Generate Chairs')}</span>
          </button>
          <button
            onClick={handleGenerateDecor}
            disabled={!hasObjects}
            className={cn(
              'flex items-center gap-2 rounded-lg px-3 py-2 text-sm transition-all',
              hasObjects
                ? 'bg-amber-600/20 text-amber-400 hover:bg-amber-600/30'
                : 'cursor-not-allowed bg-gray-700 text-gray-500'
            )}
          >
            <div className="flex gap-1">
              <Lamp className="h-4 w-4" />
              <TreePine className="h-4 w-4" />
            </div>
            <span>{t('voxel.procgen.generateDecor', 'Generate Decor')}</span>
          </button>
        </div>
      </div>

      {/* Snap Settings */}
      <div className="rounded-lg bg-gray-800 p-3">
        <h3 className="mb-2 text-xs font-medium uppercase text-gray-400">
          {t('voxel.procgen.snapSettings', 'Snap Settings')}
        </h3>
        <div className="flex flex-col gap-2">
          <label className="flex items-center justify-between">
            <span className="text-sm text-gray-300">
              {t('voxel.procgen.enableSnap', 'Enable Snap')}
            </span>
            <input
              type="checkbox"
              checked={snapConfig.enabled}
              onChange={(e) => setSnapConfig({ enabled: e.target.checked })}
              className="h-4 w-4 rounded border-gray-600 bg-gray-700 text-blue-500 focus:ring-blue-500"
            />
          </label>
          <label className="flex items-center justify-between">
            <span className="text-sm text-gray-300">
              {t('voxel.procgen.showGuides', 'Show Guides')}
            </span>
            <input
              type="checkbox"
              checked={snapConfig.showGuides}
              onChange={(e) => setSnapConfig({ showGuides: e.target.checked })}
              className="h-4 w-4 rounded border-gray-600 bg-gray-700 text-blue-500 focus:ring-blue-500"
            />
          </label>
          <div>
            <label className="mb-1 block text-sm text-gray-300">
              {t('voxel.procgen.gridSize', 'Grid Size')}
            </label>
            <input
              type="range"
              min="0.25"
              max="1"
              step="0.25"
              value={snapConfig.gridSize}
              onChange={(e) => setSnapConfig({ gridSize: parseFloat(e.target.value) })}
              className="w-full"
            />
            <div className="text-xs text-gray-400">
              {snapConfig.gridSize} {t('voxel.procgen.units', 'units')}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
